&tao_start
  n_universes = 1
  plot_file   ='$LCLS_LATTICE/bmad/tao/tao_plot.init '
  startup_file='$LCLS_LATTICE/bmad/tao/tao.startup'
/




!--------------------------------------------------------
&tao_design_lattice
  !unique_name_suffix="*::_##?"
  design_lattice(1)%file= 'cu_spec.lat.bmad'
!  combine_consecutive_elements_of_like_name = T
/

!------------------------------------------------------------------------
&tao_params
  !global%plot_on = T
  global%track_type = 'single'
  global%beam_timer_on = T
  global%random_engine = 'pseudo' ! or: 'quasi'
  global%de_lm_step_ratio = 1500
  global%optimizer = 'lmdif'
  global%n_opti_cycles = 100
  !---Bmad---
  bmad_com%radiation_damping_on = F
  bmad_com%radiation_fluctuations_on = T
/


&tao_beam_init
beam_init%random_engine = 'quasi'
ix_universe = 1
beam_saved_at =  "MARKER::*"
track_start = 'YAG03'
track_end = 'OTR2'
beam_init%position_file = '$LCLS_LATTICE/bmad/beams/YAG03_100k.h5'
beam_init%center(1) = 0.0
beam_init%center(2) = 0.0
beam_init%center(3) = 0.0
beam_init%center(4) = 0.0
beam_init%center(5) = 0.0
beam_init%center(6) = 0.0

/





&tao_d2_data
        d2_data%name = 'floor'
        universe = 1
        n_d1_data = 1
/

&tao_d1_data
        ix_d1_data = 1
        default_weight = 1
        d1_data%name = 'end'
        datum( 1) =  'floor.x'     '' '' 'OTR2'   'target' 0     1e1 
        datum( 2) =  'floor.y'     '' '' 'OTR2'   'target' 0     1e1 
        datum( 3) =  'floor.z'     '' '' 'OTR2'   'target' 0     1e1 
        datum( 4) =  'floor.theta'     '' '' 'OTR2'   'target' 0     1e1 
        datum( 5) =  's_position'  '' '' 'OTR2'   'target' 0     1e1 
/



&tao_d2_data
        d2_data%name = 'L0BBEG'
        universe = 1
        n_d1_data = 1
/

&tao_d1_data
        ix_d1_data = 1
        default_weight = 1
        d1_data%name = 'begtwiss'
        datum( 1) =  'beta.a'     '' '' 'L0BBEG'   'target' 1.70256645E+01      1e1   ! Taken from lcls_end_L0a_nominal.beam0
        datum( 2) =  'alpha.a'    '' '' 'L0BBEG'   'target'  -3.24553454E+00     1e2
        datum( 3) =  'beta.b'     '' '' 'L0BBEG'   'target' 1.68626004E+01      1e1
        datum( 4) =  'alpha.b'    '' '' 'L0BBEG'   'target' -3.20070233E+00      1e2
        datum( 5) =  'eta.x'      '' '' 'L0BBEG'   'target' 0      1e1
        datum( 6) =  'etap.x'     '' '' 'L0BBEG'   'target' 0      1e2
/  



&tao_d2_data
        d2_data%name = 'OTR2'
        universe = 1
        n_d1_data = 1
/

&tao_d1_data
        ix_d1_data = 1
        default_weight = 1
        d1_data%name = 'begtwiss'
        datum( 1) =  'beta.a'     '' '' 'OTR2'   'target'  1.11311451   1e1
        datum( 2) =  'alpha.a'    '' '' 'OTR2'   'target'  -0.06893842814 1e2
        datum( 3) =  'beta.b'     '' '' 'OTR2'   'target'  1.113049813     1e1
        datum( 4) =  'alpha.b'    '' '' 'OTR2'   'target'  -0.07029173589  1e2
        datum( 5) =  'eta.x'      '' '' 'OTR2'   'target'   0  1e1
        datum( 6) =  'etap.x'     '' '' 'OTR2'   'target'   0   1e2
/ 



!-----------------------------------------
! BPM Orbit
! Auto-generated BPM datums using: $LCLS_LATTICE/bmad/conversion/tao/create_vars_and_datums.ipynb
        
&tao_d2_data
    d2_data%name = 'orbit'
    universe = 1
    n_d1_data = 3
/    
    
&tao_d1_data
    ix_d1_data = 1
    default_weight = 1
    d1_data%name = 'x'
    default_data_type = 'bpm_orbit.x'
    default_data_source = 'lat'
    !search_for_lat_eles = "monitor::bpm*,monitor::rfb*" 
    datum(1:)%ele_name =  'BPM2', 'BPM3', 'BPM5', 'BPM6', 'BPM8', 'BPM9', 'BPM10', 'BPM11', 'BPM12',
     'BPMS1', 'BPMS2', 'BPMS3'
    datum(1:)%meas = 0
/

&tao_d1_data
    ix_d1_data = 2
    default_weight = 1
    d1_data%name = 'y'
    default_data_type = 'bpm_orbit.y'
    default_data_source = 'lat'
    !search_for_lat_eles = "monitor::bpm*,monitor::rfb*" 
    use_same_lat_eles_as = 'orbit.x'
    datum(1:)%meas = 0
/

&tao_d1_data
    ix_d1_data = 3
    default_weight = 1
    d1_data%name = 'charge'
    default_data_type = 'bunch_charge.live'
    default_data_source = 'beam'
    !search_for_lat_eles = "monitor::bpm*,monitor::rfb*" 
    use_same_lat_eles_as = 'orbit.x'
/





!-----------------------------------------


!----------------------------------------
!----------------------------------------

&tao_var
	v1_var%name = 'begtwiss'
	default_step = 1e-4
	default_universe = '1'
	ix_min_var = 1
	ix_max_var = 6
	var(1:6)%ele_name  = 'beginning', 'beginning', 'beginning', 'beginning', 'beginning', 'beginning'
    var(1:6)%attribute = 'beta_a', 'alpha_a', 'beta_b', 'alpha_b', 'eta_x', 'etap_x'
    var(1)%low_lim = 0.01
    var(3)%low_lim = 0.01
/


&tao_var
	v1_var%name = 'begorbit'
	default_step = 1e-4
	default_universe = '1'
	ix_min_var = 1
	ix_max_var = 4
	var(1:)%ele_name  = 'particle_start', 'particle_start', 'particle_start', 'particle_start'
    var(1:)%attribute = 'x', 'px', 'y', 'py'
/

&tao_var
	v1_var%name = 'L0_errors'
	default_step = 1e-4
	default_universe = '1'
	ix_min_var = 1
	!ix_max_var = 4
	var(1:)%ele_name  = 'L0A', 'L0B', 'L0A', 'L0B', 'QA01', 'QA02', 'QA01', 'QA02'
    !var(1:)%attribute = 'x_pitch', 'y_pitch', 'x_pitch', 'y_pitch'
    var(1:)%attribute = 'bl_hkick', 'bl_hkick', 'bl_vkick', 'bl_vkick', 'bl_hkick', 'bl_hkick', 'bl_vkick', 'bl_vkick'
/




&tao_var
    v1_var%name = 'q.OTR2'
	default_step = 1e-4
	default_attribute = 'K1'
	var(1:)%ele_name = 'QA01','QA02', 'QE01', 'QE02', 'QE03', 'QE04'
/




!----------------------------------------
! Correctors
! Auto-generated corrector datums using: $LCLS_LATTICE/bmad/conversion/tao/create_vars_and_datums.ipynb
        
&tao_var
    v1_var%name = 'xcor'
    default_step = 1e-2
    default_attribute = 'bl_kick'
    var(1:)%ele_name =  'XC00', 'XC01', 'XC02', 'XC03', 'XC04', 'XC05', 'XC06', 'XC07', 'XC08', 'XCS1',
     'XCS2'
/


&tao_var
    v1_var%name = 'ycor'
    default_step = 1e-2
    default_attribute = 'bl_kick'
    var(1:)%ele_name =  'YC00', 'YC01', 'YC02', 'YC03', 'YC04', 'YC05', 'YC06', 'YC07', 'YC08', 'YCS1',
     'YCS2'
/

!----------------------------------------
