# conda env create -f environment.yml
name: lcls-lattice-dev
channels:
  - conda-forge
dependencies:
  - python>=3.9
  - bmad=20260223.1
  - pytao=0.5.7
  - distgen
  - impact-t =*=mpi_openmpi*
  - genesis4 >=4.6.6=mpi_openmpi*
  - lume-genesis
  - lume-impact
  - openPMD-beamphysics 
  - pytest
  - ipykernel
  - ipywidgets
  - jupyterlab
  - openpyxl
