# conda env create -f environment-prod.yml
name: lcls-lattice-prod
channels:
  - conda-forge
dependencies:
  - python=3.12
  - bmad=20260223.1
  - pytao=0.5.7
  - distgen
  - impact-t =*=mpi_openmpi*
  - genesis4 >=4.6.6=mpi_openmpi*
  - lume-genesis
  - lume-impact
  - openPMD-beamphysics=0.14.0
  - pytest
  - ipykernel
  - ipywidgets
  - jupyterlab
  - openpyxl
