&tao_start
  n_universes = 1
  plot_file   ='$LCLS2_LATTICE/bmad/tao/tao_plot.init '
  startup_file='$LCLS2_LATTICE/bmad/tao/tao.startup'
/




!--------------------------------------------------------
&tao_design_lattice
 design_lattice(1)%file= 'sol.lat.bmad'
/

!------------------------------------------------------------------------
&tao_params
  !global%plot_on = T
  global%track_type = 'single'
  global%beam_timer_on = T
  global%random_engine = 'pseudo' ! or: 'quasi'
  global%de_lm_step_ratio = 1500
  global%optimizer = 'lmdif'
  global%n_opti_cycles = 100
  !---Bmad---
  bmad_com%radiation_damping_on = F
  bmad_com%radiation_fluctuations_on = T
/


&tao_d2_data
        d2_data%name = 'twiss'
        universe = 1
        n_d1_data = 4
/

&tao_d1_data
        ix_d1_data = 1
        default_weight = 1
        d1_data%name = 'endtwiss'
        datum( 1) =  'beta.a'     '' '' 'Mar.END'   'target' 10 1e1
        datum( 2) =  'alpha.a'    '' '' 'Mar.END'   'target' 0 1e2
        datum( 3) =  'beta.b'     '' '' 'Mar.END'   'target' 10 1e1
        datum( 4) =  'alpha.b'    '' '' 'Mar.END'  'target' 0 1e2
/  
&tao_d1_data
        ix_d1_data = 2
        default_weight = 1
        d1_data%name = 'maxs'
        datum( 1) =  'beta.a'     '' 'Mar.BEG' 'Mar.END'   'max' 20 1e1   
        datum( 2) =  'beta.b'     '' 'Mar.BEG' 'Mar.END'    'max' 20 1e1   
/
&tao_d1_data
        ix_d1_data = 3
        default_weight = 1e5
        d1_data%name = 'average'
        datum( 1) =  'beta.a'     '' 'Mar.BEG' 'Mar.END'   'average' 20 1e1   
        datum( 2) =  'beta.b'     '' 'Mar.BEG' 'Mar.END'   'average' 20 1e1   

/
&tao_d1_data
        ix_d1_data = 4
        default_weight = 1
        d1_data%name = 'stability'
        datum( 1) =  'unstable.ring'     '' '' ''   'target' 0  1e15 
/



!----------------------------------------
!----------------------------------------


! Use this to vary the input Twiss. Only for an open geometry. 
!&tao_var
	v1_var%name = 'begtwiss'
	default_step = 1e-4
	default_universe = '1'
	ix_min_var = 1
	ix_max_var = 6
	var(1:6)%ele_name  = 'beginning', 'beginning', 'beginning', 'beginning', 'beginning', 'beginning'
    var(1:6)%attribute = 'beta_a', 'alpha_a', 'beta_b', 'alpha_b', 'eta_x', 'etap_x'
    var(1)%low_lim = 0.01
    var(3)%low_lim = 0.01
/


&tao_var
    v1_var%name = 'sols'
	default_step = 1e-4
	default_attribute = 'bs_field'
	default_key_bound = T
	default_key_delta = 0.01
    var(1:)%ele_name = 'sol1'
/



