&tao_start
  n_universes = 1
  plot_file   ='tao_plot.init'
  startup_file='tao.startup'
/

!--------------------------------------------------------
&tao_design_lattice
  !unique_name_suffix="*::_##?"
  design_lattice(1)%file='sc_hxr2.lat.bmad'
  design_lattice(1)%slice_lattice = "OTRC006:HXRSTART"
/

!------------------------------------------------------------------------
&tao_params
  global%plot_on = T
  global%track_type = 'beam'
  global%beam_timer_on = T
  global%random_engine = 'pseudo' ! or: 'quasi'
  global%de_lm_step_ratio = 1500
  global%optimizer = 'lmdif'
  global%n_opti_cycles = 100
  !---Bmad---
  bmad_com%radiation_damping_on = F
  bmad_com%radiation_fluctuations_on = T
/


&tao_beam_init
ix_universe = 1
!saved_at =  "MARKER::*"
track_start = 'OTRC006'
track_end = 'HXRSTART'
beam_init%n_particle = 1000
beam_init%random_engine = 'quasi' ! or 'pseudo'
beam_init%bunch_charge = 300.0e-12
beam_init%a_norm_emit = 1.5e-6
beam_init%b_norm_emit = 1.5e-6
beam_init%n_bunch = 1
beam_init%sig_pz = 1e-3
beam_init%sig_z = 0.8e-3
/

!---------------------------------------------------------------------------------------
! BC1

&tao_d2_data
        d2_data%name = 'BC1'
        universe = 1
        n_d1_data = 2
/
&tao_d1_data
        ix_d1_data = 1
        default_weight = 1
        d1_data%name = 'begtwiss'
        datum( 1) =  'beta.a'     '' '' 'BEGBC1B'   'target'  3.870395077E+01   1e1
        datum( 2) =  'alpha.a'    '' '' 'BEGBC1B'   'target'  4.476022866E-01  1e2
        datum( 3) =  'beta.b'     '' '' 'BEGBC1B'   'target'  3.109163641E+01     1e1
        datum( 4) =  'alpha.b'    '' '' 'BEGBC1B'   'target'  -7.975687433E-01  1e2
        datum( 5) =  'eta.x'      '' '' 'BEGBC1B'   'target'   0  1e1
        datum( 6) =  'etap.x'     '' '' 'BEGBC1B'   'target'   0   1e2
/  

&tao_d1_data
        ix_d1_data = 2
        default_weight = 1
        d1_data%name = 'r56'
        datum( 1) =  'r56_compaction'     'BEGBC1B' '' 'ENDBC1B'  'target' 45e-3  1e1
/


!---------------------------------------------------------------------------------------
! COL1

&tao_d2_data
        d2_data%name = 'COL1'
        universe = 1
        n_d1_data = 1
/
&tao_d1_data
        ix_d1_data = 1
        default_weight = 1
        d1_data%name = 'endtwiss'
        datum( 1) =  'beta.a'     '' '' 'ENDCOL1'   'target'  23.912    1e1
        datum( 2) =  'alpha.a'    '' '' 'ENDCOL1'   'target' 0.855 1e2
        datum( 3) =  'beta.b'     '' '' 'ENDCOL1'   'target' 7.954     1e1
        datum( 4) =  'alpha.b'    '' '' 'ENDCOL1'   'target' -0.793  1e2
        datum( 5) =  'eta.x'      '' '' 'ENDCOL1'   'target'   0  1e1
        datum( 6) =  'etap.x'     '' '' 'ENDCOL1'   'target'   0   1e2
/  





!---------------------------------------------------------------------------------------
! BC2

&tao_d2_data
        d2_data%name = 'BC2'
        universe = 1
        n_d1_data = 2
/
&tao_d1_data
        ix_d1_data = 1
        default_weight = 1
        d1_data%name = 'begtwiss'
        datum( 1) =  'beta.a'     '' '' 'BEGBC2B'   'target'  3.870395077E+01   1e1
        datum( 2) =  'alpha.a'    '' '' 'BEGBC2B'   'target'  4.476022866E-01    1e2
        datum( 3) =  'beta.b'     '' '' 'BEGBC2B'   'target'  3.109163641E+01     1e1
        datum( 4) =  'alpha.b'    '' '' 'BEGBC2B'   'target'  -7.975687433E-01   1e2
        datum( 5) =  'eta.x'      '' '' 'BEGBC2B'   'target'   0  1e1
        datum( 6) =  'etap.x'     '' '' 'BEGBC2B'   'target'   0   1e2
/  

&tao_d1_data
        ix_d1_data = 2
        default_weight = 1
        d1_data%name = 'r56'
        datum( 1) =  'r56_compaction'     'BEGBC2B' '' 'ENDBC2B'  'target' 45e-3  1e1
/




!---------------------------------------------------------------------------------------
! EMIT2

&tao_d2_data
        d2_data%name = 'EMIT2'
        universe = 1
        n_d1_data = 1
/
&tao_d1_data
        ix_d1_data = 1
        default_weight = 1
        d1_data%name = 'endtwiss'
        datum( 1) =  'beta.a'     '' '' 'ENDEMIT2'   'target'  48.080    1e1
        datum( 2) =  'alpha.a'    '' '' 'ENDEMIT2'   'target'  1.354  1e2
        datum( 3) =  'beta.b'     '' '' 'ENDEMIT2'   'target'  10.447      1e1
        datum( 4) =  'alpha.b'    '' '' 'ENDEMIT2'   'target'  -0.746   1e2
        datum( 5) =  'eta.x'      '' '' 'ENDEMIT2'   'target'   0  1e1
        datum( 6) =  'etap.x'     '' '' 'ENDEMIT2'   'target'   0   1e2
/  





 

!---------------------------------------------------------------------------------------
! L1


&tao_d2_data
        d2_data%name = 'L1'
        universe = 1
        n_d1_data = 2
/

&tao_d1_data
        ix_d1_data = 1
        default_weight = 1
        d1_data%name = 'energy'
        datum( 1) =  'orbit.e_tot'     '' '' 'ENDL1B'   'target'  250e6  1e1
/

&tao_d1_data
    ix_d1_data = 2
    d1_data%name = 'endtwiss'
    datum( 1) =  'beta.a'     '' '' 'ENDL1B'   'target'   3.870395077E+01   1e1
    datum( 2) =  'alpha.a'    '' '' 'ENDL1B'   'target'   4.476022866E-01   1e1
    datum( 3) =  'beta.b'     '' '' 'ENDL1B'   'target'   3.109163641E+01   1e1
    datum( 4) =  'alpha.b'    '' '' 'ENDL1B'   'target'  -7.975687433E-01   1e1
    datum( 5) =  'eta.x'      '' '' 'ENDL1B'   'target'  -4.447171945E-18   1e1
    datum( 6) =  'etap.x'     '' '' 'ENDL1B'   'target'  -1.665944118E-18   1e1
/



!---------------------------------------------------------------------------------------
! L2

&tao_d2_data
        d2_data%name = 'L2'
        universe = 1
        n_d1_data = 2
/

&tao_d1_data
        ix_d1_data = 1
        default_weight = 1
        d1_data%name = 'energy'
        datum( 1) =  'orbit.e_tot'     '' '' 'ENDL2B'   'target'  1600e6  1e1
/

&tao_d1_data
    ix_d1_data = 2
    d1_data%name = 'endtwiss'
    datum( 1) =  'beta.a'     '' '' 'ENDL2B'   'target'   2.301739816E+02   1e1
    datum( 2) =  'alpha.a'    '' '' 'ENDL2B'   'target'  -3.315233808E+00   1e1
    datum( 3) =  'beta.b'     '' '' 'ENDL2B'   'target'   1.535195604E+01   1e1
    datum( 4) =  'alpha.b'    '' '' 'ENDL2B'   'target'  -2.950181911E-01   1e1
    datum( 5) =  'eta.x'      '' '' 'ENDL2B'   'target'  -1.435337641E-12   1e1
    datum( 6) =  'etap.x'     '' '' 'ENDL2B'   'target'   2.967880755E-14   1e1
/  


!---------------------------------------------------------------------------------------
! L3

&tao_d2_data
        d2_data%name = 'L3'
        universe = 1
        n_d1_data = 2
/


&tao_d1_data
        ix_d1_data = 1
        default_weight = 1
        d1_data%name = 'energy'
        datum( 1) =  'orbit.e_tot'     '' '' 'ENDL3B'   'target'  4000e6  1e1
/

&tao_d1_data
    ix_d1_data = 2
    d1_data%name = 'endtwiss'
    datum( 1) =  'beta.a'     '' '' 'ENDL3B'   'target'   28.098   1e1
    datum( 2) =  'alpha.a'    '' '' 'ENDL3B'   'target'  -1.3  1e1
    datum( 3) =  'beta.b'     '' '' 'ENDL3B'   'target'   43.518  1e1
    datum( 4) =  'alpha.b'    '' '' 'ENDL3B'   'target'   1.863   1e1
    datum( 5) =  'eta.x'      '' '' 'ENDL3B'   'target'   0   1e1
    datum( 6) =  'etap.x'     '' '' 'ENDL3B'   'target'   0   1e1
/

!-----------------------------------------------------------------------------------------

&tao_var
    v1_var%name = 'begtwiss'
    default_step = 1e-4
    default_universe = '1'
    ix_min_var = 1
    ix_max_var = 6
    var(1:6)%ele_name  = 'beginning', 'beginning', 'beginning', 'beginning', 'beginning', 'beginning'
    var(1:6)%attribute = 'beta_a', 'alpha_a', 'beta_b', 'alpha_b', 'eta_x', 'etap_x'
    var(1)%low_lim = 0.01
    var(3)%low_lim = 0.01
/

&tao_var
    v1_var%name = 'q_L2'
	default_step = 1e-4
	default_attribute = 'K1'
	var(1:)%ele_name = 'QCM04', 'QCM08', 'QCM11', 'QCM15'
/

&tao_var
    v1_var%name = 'q_L3'
	default_step = 1e-4
	default_attribute = 'K1'
	var(1:)%ele_name = 'QCM17', 'QCM22', 'QCM29', 'QCM35'
/



&tao_var
    v1_var%name = 'linac_phase'
	default_step = 0.1
	default_attribute = 'phase_deg'
	var(1:)%ele_name = 'SC_L1', 'SC_L1H', 'SC_L2', 'SC_L3'
/

&tao_var
    v1_var%name = 'q_COL1'
	default_step = 1e-4
	default_attribute = 'K1'
	var(1:)%ele_name = 'QC101', 'QC102', 'QC103', 'QC104'
/

&tao_var
    v1_var%name = 'q_EMIT2'
	default_step = 1e-4
	default_attribute = 'K1'
	var(1:)%ele_name = 'QE201', 'QE202', 'QE203', 'QE204'
/


&tao_var
    v1_var%name = 'bc1'
    default_step = 0.01
    default_attribute = 'angle_deg'
    var(1:)%low_lim = -8.35
    var(1:)%high_lim = 0
    var(1:)%ele_name = 'SC_BC1'
/

&tao_var
    v1_var%name = 'bc2'
    default_step = 0.01
    default_attribute = 'angle_deg'
    var(1:)%low_lim =  0 
    var(1:)%high_lim =  9.1
    var(1:)%ele_name = 'SC_BC2'
/


!----------------------------------------
! Correctors
! Auto-generated corrector datums using: $LCLS_LATTICE/bmad/conversion/tao/create_vars_and_datums.ipynb
        
!&tao_var
!    v1_var%name = 'xcor'
!    default_step = 1e-2
!    default_attribute = 'bl_kick'
!    var(1:)%ele_name =  'XC01B', 'XC02B', 'XC03B', 'XC04B', 'XC05B', 'XCM01', 'XC0H01',
!     'XC0H03', 'XC0H05', 'XC0H07', 'XCHD01', 'XCHD03', 'XCC000', 'XCC004',
!     'XCC006', 'XCC008', 'XCC010', 'XCC012', 'XCM02', 'XCM03', 'XC1C00', 'XCM12B',
!     'XCC101', 'XCC104', 'XCC106', 'XCC108', 'XCC110', 'XCC112', 'XCM04', 'XCM05',
!     'XCM06', 'XCM07', 'XCM08', 'XCM09', 'XCM10', 'XCM11', 'XCM12', 'XCM13', 'XCM14',
!     'XCM15', 'XC2C00', 'XCE202', 'XCE204', 'XCM16', 'XCM17', 'XCM18', 'XCM19',
!     'XCM20', 'XCM21', 'XCM22', 'XCM23', 'XCM24', 'XCM25', 'XCM26', 'XCM27', 'XCM28',
!     'XCM29', 'XCM30', 'XCM31', 'XCM32', 'XCM33', 'XCM34', 'XCM35', 'XCX01',
!     'XCDOG1', 'XCDOG3', 'XCDOG5', 'XCDOG7', 'XCL1P', 'XCL3P', 'XCL5P', 'XCBP11',
!     'XCBP13', 'XCBP14', 'XCBP15', 'XCBP16', 'XCBP17', 'XCBP18', 'XCBP19',
!     'XCBP20', 'XCBP21', 'XCBP22', 'XCBP23', 'XCBP24', 'XCBP25', 'XCBP26',
!     'XCBP27', 'XCBP35', 'XCBP28', 'XCSP1H', 'XCSP3H', 'XCSP5H', 'XCSP7H',
!     'XCSP9H', 'XCSP11H', 'XCSP13H', 'XCBSYQ3', 'XCAPM2', 'XCBSYQ5', 'XCA0',
!     'XCVM2', 'XCVB2', 'XCVM3', 'XCDL1', 'XCQT12', 'XCDL2', 'XCQT22', 'XCDL3',
!     'XCQT32', 'XCDL4', 'XCQT42', 'XCEM2', 'XCEM4', 'XCE31', 'XCE33', 'XCE35',
!     'XCUM1', 'XCUM3', 'XCHX13', 'XCHX14', 'XCHX15', 'XCHX16', 'XCHX17',
!     'XCHX18', 'XCHX19', 'XCHX20', 'XCHX21', 'XCHX22', 'XCHX23', 'XCHX24',
!     'XCHX25', 'XCHX26', 'XCHX27', 'XCHX28', 'XCHX29', 'XCHX30', 'XCHX31',
!     'XCHX32', 'XCHX33', 'XCHX34', 'XCHX35', 'XCHX36', 'XCHX37', 'XCHX38',
!     'XCHX39', 'XCHX40', 'XCHX41', 'XCHX42', 'XCHX43', 'XCHX44', 'XCHX45',
!     'XCHX46', 'XCHX47', 'XCUE2', 'XCD3', 'XCDD'
!/
!
!
!&tao_var
!    v1_var%name = 'ycor'
!    default_step = 1e-2
!    default_attribute = 'bl_kick'
!    var(1:)%ele_name =  'YC01B', 'YC02B', 'YC03B', 'YC04B', 'YC05B', 'YCM01', 'YC0H01',
!     'YC0H03', 'YC0H05', 'YC0H07', 'YCHD01', 'YCHD03', 'YCC000', 'YCC003',
!     'YCC005', 'YCC007', 'YCC009', 'YCC011', 'YCM02', 'YCM03', 'YC1C00', 'YCM12B',
!     'YCC101', 'YCC105', 'YCC107', 'YCC109', 'YCC111', 'YCM04', 'YCM05', 'YCM06',
!     'YCM07', 'YCM08', 'YCM09', 'YCM10', 'YCM11', 'YCM12', 'YCM13', 'YCM14', 'YCM15',
!     'YC2C00', 'YCE201', 'YCE203', 'YCM16', 'YCM17', 'YCM18', 'YCM19', 'YCM20',
!     'YCM21', 'YCM22', 'YCM23', 'YCM24', 'YCM25', 'YCM26', 'YCM27', 'YCM28', 'YCM29',
!     'YCM30', 'YCM31', 'YCM32', 'YCM33', 'YCM34', 'YCM35', 'YCX02', 'YCDOG0',
!     'YCDOG2', 'YCDOG4', 'YCDOG6', 'YCDOG8', 'YCL2P', 'YCL4P', 'YCBP10', 'YCBP12',
!     'YCBP13', 'YCBP14', 'YCBP15', 'YCBP16', 'YCBP17', 'YCBP18', 'YCBP19',
!     'YCBP20', 'YCBP21', 'YCBP22', 'YCBP23', 'YCBP24', 'YCBP25', 'YCBP26',
!     'YCBP27', 'YCBP35', 'YCBP28', 'YCSP2H', 'YCSP4H', 'YCSP6H', 'YCSP8H',
!     'YCSP10H', 'YCSP12H', 'YCBSYQ4', 'YCAPM2', 'YCBSYQ6', 'YCA0', 'YCVM1',
!     'YCVB1', 'YCVB3', 'YCVM4', 'YCDL1', 'YCQT12', 'YCDL2', 'YCQT21', 'YCDL3',
!     'YCQT32', 'YCDL4', 'YCQT42', 'YCEM1', 'YCEM3', 'YCE32', 'YCE34', 'YCE36',
!     'YCUM2', 'YCUM4', 'YCHX13', 'YCHX14', 'YCHX15', 'YCHX16', 'YCHX17',
!     'YCHX18', 'YCHX19', 'YCHX20', 'YCHX21', 'YCHX22', 'YCHX23', 'YCHX24',
!     'YCHX25', 'YCHX26', 'YCHX27', 'YCHX28', 'YCHX29', 'YCHX30', 'YCHX31',
!     'YCHX32', 'YCHX33', 'YCHX34', 'YCHX35', 'YCHX36', 'YCHX37', 'YCHX38',
!     'YCHX39', 'YCHX40', 'YCHX41', 'YCHX42', 'YCHX43', 'YCHX44', 'YCHX45',
!     'YCHX46', 'YCHX47', 'YCUE1', 'YCD3', 'YCDD'
!/

!----------------------------------------


