&tao_start
  n_universes = 1
  plot_file   ='$LCLS_LATTICE/bmad/tao/tao_plot.init '
  startup_file='$LCLS_LATTICE/bmad/tao/tao.startup'
/




!--------------------------------------------------------
&tao_design_lattice
  !unique_name_suffix="*::_##?"
  design_lattice(1)%file='sc_inj.lat.bmad'
/

!------------------------------------------------------------------------
&tao_params
  !global%plot_on = T
  global%track_type = 'single'
  global%beam_timer_on = T
  global%random_engine = 'pseudo' ! or: 'quasi'
  global%de_lm_step_ratio = 1500
  global%optimizer = 'lmdif'
  global%n_opti_cycles = 100
  !---Bmad---
  bmad_com%radiation_damping_on = F
  bmad_com%radiation_fluctuations_on = T
/




&tao_beam_init
beam_init%random_engine = 'quasi'
ix_universe = 1
beam_saved_at =  "MARKER::*"
!track_start = 'OTR2'
!track_end = 'DBMARK82'
beam_init%position_file = 'cathode_probe_particles.h5'
/




!---------------------------------------------------------------------------------------
! L0

&tao_d2_data
        d2_data%name = 'L0B'
        universe = 1
        n_d1_data = 2
/
&tao_d1_data
        ix_d1_data = 1
        default_weight = 1
        d1_data%name = 'energy'
        datum( 1) =  'orbit.e_tot'     '' '' 'BEAM0'   'target'  100e6  1e1
/


&tao_d1_data
    ix_d1_data = 2
    d1_data%name = 'endtwiss'
    datum( 1) =  'beta.a'     '' '' 'BEAM0'   'target'  50.4    1e1
    datum( 2) =  'alpha.a'    '' '' 'BEAM0'   'target' -1.75    1e1
    datum( 3) =  'beta.b'     '' '' 'BEAM0'   'target'  50.4   1e1
    datum( 4) =  'alpha.b'    '' '' 'BEAM0'   'target' -1.75   1e1
    datum( 5) =  'eta.x'      '' '' 'BEAM0'   'target'  0    1e1
    datum( 6) =  'etap.x'     '' '' 'BEAM0'   'target'  0    1e1
/  

!---------------------------------------------------------------------------------------
! HTR

&tao_d2_data
        d2_data%name = 'HTR'
        universe = 1
        n_d1_data = 1
/
&tao_d1_data
        ix_d1_data = 1
        default_weight = 1
        d1_data%name = 'begtwiss'
        datum( 1) =  'beta.a'     '' '' 'HTRUNDB'   'target'  10   1e1
        datum( 2) =  'alpha.a'    '' '' 'HTRUNDB'   'target' 0  1e2
        datum( 3) =  'beta.b'     '' '' 'HTRUNDB'   'target'  10    1e1
        datum( 4) =  'alpha.b'    '' '' 'HTRUNDB'   'target'  0  1e2
        datum( 5) =  'eta.x'      '' '' 'HTRUNDB'   'target'   0  1e1
        datum( 6) =  'etap.x'     '' '' 'HTRUNDB'   'target'   0   1e2
/   



!-----------------------------------------
!-----------------------------------------------------------------------------------------




&tao_var
    v1_var%name = 'begtwiss'
    default_step = 1e-4
    default_universe = '1'
    ix_min_var = 1
    ix_max_var = 6
    var(1:6)%ele_name  = 'beginning', 'beginning', 'beginning', 'beginning', 'beginning', 'beginning'
    var(1:6)%attribute = 'beta_a', 'alpha_a', 'beta_b', 'alpha_b', 'eta_x', 'etap_x'
    var(1)%low_lim = 0.01
    var(3)%low_lim = 0.01
/





&tao_var
    v1_var%name = 'q.HTR'
    default_step = 1e-4
    default_attribute = 'K1'
    search_for_lat_eles = 'quad::Q0H*'
/