&tao_start
  n_universes = 1
  plot_file   ='$LCLS_LATTICE/bmad/tao/tao_plot.init '
!  startup_file='$LCLS_LATTICE/bmad/tao/tao.startup'
 startup_file='Setup.tao'
/




!--------------------------------------------------------
&tao_design_lattice
  !unique_name_suffix="*::_##?"
  design_lattice(1)%file= 'lat.bmad'
  
 ! design_lattice(1)%slice_lattice = 'L1X:DTDUND2'
  design_lattice(1)%slice_lattice = 'QVM1:DTDUND2'
  !  design_lattice(1)%slice_lattice = 'QVM1:CEDL3'
  
  
!  combine_consecutive_elements_of_like_name = T
/

!------------------------------------------------------------------------
&tao_params
  !global%plot_on = T
  global%track_type = 'single'
  global%beam_timer_on = T
  global%random_engine = 'pseudo' ! or: 'quasi'
  global%de_lm_step_ratio = 1500
  global%optimizer = 'lmdif'
  global%n_opti_cycles = 100
  global%var_out_file = ''
  !---Bmad---
  bmad_com%radiation_damping_on = F
  bmad_com%radiation_fluctuations_on = T
/


!&tao_beam_init
!beam_init%random_engine = 'quasi'
!ix_universe = 1
!beam_saved_at =  "MARKER::*"
!track_start = 'OTR2'
!!track_end = 'DBMARK82'
!!track_end = 'BC1CEND'
!beam_init%position_file = '$LCLS_LATTICE/bmad/beams/OTR2_250pC_rescaleto540um_solGTF1M_flat_scattered_20keV_100k.beam0'
!!beam_init%position_file = 'beam_1.hdf5'
!beam_init%center(1) = 0.0
!beam_init%center(2) = 0.0
!beam_init%center(3) = 0.0
!beam_init%center(4) = 0.0
!beam_init%center(5) = 0.0
!beam_init%center(6) = 0.0
!
!/
!




!----------------------------------------
! Aperture for Orbit Plot


&tao_d2_data 
 d2_data%name = "aperture" 
 universe = '*' 
 n_d1_data=2 
/ 
&tao_d1_data 
 ix_d1_data = 1 
 d1_data%name = "p" 
 ix_min_data = 0 
 ix_max_data = 8000 
 default_data_source      = 'lat' 
 default_data_type     = 'element_attrib.x2_limit' 
 search_for_lat_eles = 'rcollimator::*,marker::APERTURE_*'  ! Special apertures put into lattice file as markers
/ 
&tao_d1_data 
 ix_d1_data = 2 
 d1_data%name = "n" 
 ix_min_data = 0 
 ix_max_data = 8000 
 default_data_source      = 'lat' 
 default_data_type     = 'element_attrib.x1_limit' 
 use_same_lat_eles_as = 'aperture.p' 
/






!----------------------------------------
! Orbit 

&tao_d2_data
    d2_data%name = "orbit"
    universe = 1
    n_d1_data = 5
/

&tao_d1_data
    ix_d1_data = 1
    default_weight = 1
    d1_data%name = 'x'
    default_data_type = 'bpm_orbit.x'
    default_data_source = 'lat'
    search_for_lat_eles = "Monitor::BPM*"
/

&tao_d1_data
    ix_d1_data = 2
    default_weight = 1
    d1_data%name = 'y'
    default_data_type = 'bpm_orbit.y'
    default_data_source = 'lat'
    search_for_lat_eles = "Instrument::BPM*,Instrument::RFB*"
/

&tao_d1_data
    ix_d1_data = 3
    default_weight = 1
    d1_data%name = 'profx'
    default_data_type = 'orbit.x'
    default_data_source = 'lat'
    search_for_lat_eles = "Instrument::YAG*,Instrument::OTR*"
/

&tao_d1_data
    ix_d1_data = 4
    default_weight = 1
    d1_data%name = 'profy'
    default_data_type = 'orbit.y'
    default_data_source = 'lat'
    search_for_lat_eles = "Instrument::YAG*,Instrument::OTR*"
/

&tao_d1_data
    ix_d1_data = 5
    default_weight = 1
    d1_data%name = 'e'
    default_data_type = 'orbit.e_tot'
    default_data_source = 'lat'
    search_for_lat_eles = "Instrument::BPM*,Instrument::RFB*"
/




!----------------------------------------

&tao_d2_data
    d2_data%name = "loss"
    universe = 1
    n_d1_data = 1
/

&tao_d1_data

  ix_d1_data = 1
        default_weight = 1
        d1_data%name = 'rel_point'
        datum( 1) =  'unstable.orbit'     '' '' 'CEDL3'   'target'  147     1  ! Reference element at the end, this is the ix requested loss before that. 
/




!----------------------------------------
!----------------------------------------


&tao_var
    v1_var%name = 'xcor'
        default_step = 1e-6
        default_attribute = 'bl_kick'
       !  default_attribute = 'hkick'
default_merit_type = 'target'
        var(1:)%ele_name =  'XCVM2', 'XCVB2','XCVM3','XCDL1' ,'XCQT12','XCDL2' ,'XCQT22','XCDL3','XCQT32','XCDL4','XCQT42','XCEM2','XCEM4','XCE31','XCE33','XCE35','XCUM1','XCUM3'
        var(1:)%high_lim = 6.000e-03, 3.000e-03, 6.000e-03, 6.000e-03, 0.000e+00, 6.000e-03, 1.200e-02, 6.000e-03, 8.950e-03, 8.950e-03, 1.200e-02, 6.000e-03, 6.000e-03, 6.000e-03, 6.000e-03, 6.000e-03, 6.000e-03, 6.000e-03
        var(1:)%low_lim = -6.000e-03, -3.000e-03, -6.000e-03, -6.000e-03, -1.200e-02, -6.000e-03, 0.000e+00, -6.000e-03, -8.950e-03, -8.950e-03, -1.200e-02, -6.000e-03, -6.000e-03, -6.000e-03, -6.000e-03, -6.000e-03, -6.000e-03, -6.000e-03


default_key_bound = T
default_key_delta = 1e-4
/

&tao_var
    v1_var%name = 'mykick.x'
        default_step = 1e-6
        default_attribute = 'bl_kick'
    search_for_lat_eles = 'hkicker::XX*'
    
default_merit_type = 'limit'
default_low_lim = -2e-4
default_high_lim = 2e-4  
default_key_bound = T
default_key_delta = 1e-5
/

&tao_var
    v1_var%name = 'ycor'
    default_step = 1e-2
    default_attribute = 'bl_kick'
    var(1:)%ele_name =  'YC00', 'YC01', 'YC02', 'YC03', 'YC04', 'YC05', 'YC06', 'YC07', 'YC08', 'YC09',
     'YC10', 'YC21102', 'YC21136', 'YC21166', 'YC21174', 'YC21192',
     'YC21276', 'YC21303', 'YC21325', 'YC21403', 'YC21503', 'YC21603',
     'YC21703', 'YC21803', 'YC21900', 'YC22203', 'YC22303', 'YC22403',
     'YC22503', 'YC22603', 'YC22703', 'YC22803', 'YC22900', 'YC23203',
     'YC23303', 'YC23403', 'YC23503', 'YC23603', 'YC23703', 'YC23803',
     'YC23900', 'YC24203', 'YC24303', 'YC24403', 'YC24503', 'YC24603',
     'YC24703', 'YC24900', 'YC25203', 'YC25303', 'YC25403', 'YC25503',
     'YC25603', 'YC25703', 'YC25803', 'YC25900', 'YC26203', 'YC26303',
     'YC26403', 'YC26503', 'YC26603', 'YC26703', 'YC26803', 'YC26900',
     'YC27203', 'YC27303', 'YC27403', 'YC27503', 'YC27603', 'YC27703',
     'YC27803', 'YC27900', 'YC28203', 'YC28303', 'YC28403', 'YC28503',
     'YC28603', 'YC28703', 'YC28803', 'YC28900', 'YC29203', 'YC29303',
     'YC29403', 'YC29503', 'YC29603', 'YC29703', 'YC29803', 'YC29900',
     'YC30203', 'YC30303', 'YC30403', 'YC30503', 'YC30603', 'YC30703',
     'YC30803', 'YC30900', 'YCBSYQ1', 'YCBSYQ4', 'YCAPM2', 'YCBSYQ6', 'YCA0',
     'YCVM1', 'YCVB1', 'YCVB3', 'YCVM4', 'YCDL1', 'YCQT12', 'YCDL2', 'YCQT21',
     'YCDL3', 'YCQT32', 'YCDL4', 'YCQT42', 'YCEM1', 'YCEM3', 'YCE32', 'YCE34',
     'YCE36', 'YCUM2', 'YCUM4', 'YCHX13', 'YCHX14', 'YCHX15', 'YCHX16', 'YCHX17',
     'YCHX18', 'YCHX19', 'YCHX20', 'YCHX21', 'YCHX22', 'YCHX23', 'YCHX24',
     'YCHX25', 'YCHX26', 'YCHX27', 'YCHX28', 'YCHX29', 'YCHX30', 'YCHX31',
     'YCHX32', 'YCHX33', 'YCHX34', 'YCHX35', 'YCHX36', 'YCHX37', 'YCHX38',
     'YCHX39', 'YCHX40', 'YCHX41', 'YCHX42', 'YCHX43', 'YCHX44', 'YCHX45',
     'YCHX46', 'YCHX47', 'YCUE1', 'YCD3', 'YCDD'
/


