!shape(i) = "<key>", "<name>", "<shape>", "<color>", "<v_size>", "<print_Label>" 
!&element_shapes_lat_layout
&lat_layout_drawing 
  ele_shape(1) = "Quadrupole::*"  "asym_var_box"  "Blue"   .5     'none'
  ele_shape(2) = "SBend::*"       "Box"          "Red"    1   'none'
  ele_shape(3) = "lcavity::*"     "Box"          "Green"   .2    'none'
  ele_shape(4) = "wiggler::*"     "Box"          "Orange"  .5    'none'
  ele_shape(5) = "SOLENOID::*"    "box"          "Blue"    1   'none'
/       

! Colors: 
!"BLACK" 
!"RED" 
!"ORANGE" 
!"MAGENTA" 
!"YELLOW" 
!"GREEN" 
!"CYAN" 
!"BLUE" 
!"PURPLE" 


