&tao_start
  n_universes = 1
  plot_file   ='$LCLS_LATTICE/bmad/tao/tao_plot.init '
  startup_file='$LCLS_LATTICE/bmad/tao/tao.startup'
/




!--------------------------------------------------------
&tao_design_lattice
  !unique_name_suffix="*::_##?"
  design_lattice(1)%file='sc_gunb.lat.bmad'
/

!------------------------------------------------------------------------
&tao_params
  !global%plot_on = T
  global%track_type = 'single'
  global%beam_timer_on = T
  global%random_engine = 'pseudo' ! or: 'quasi'
  global%de_lm_step_ratio = 1500
  global%optimizer = 'lmdif'
  global%n_opti_cycles = 100
  !---Bmad---
  bmad_com%radiation_damping_on = F
  bmad_com%radiation_fluctuations_on = T
/



&tao_d2_data
        d2_data%name = 'L0'
        universe = 1
        n_d1_data = 2
/
&tao_d1_data
        ix_d1_data = 1
        default_weight = 1
        d1_data%name = 'energy'
        datum( 1) =  'orbit.e_tot'     '' '' 'ENDL0B'   'target'  100e6  1e1
/
&tao_d1_data
    ix_d1_data = 2
    d1_data%name = 'endtwiss'
    datum( 1) =  'beta.a'     '' '' 'ENDL0B'   'target'   2.124671319E+01   1e1
    datum( 2) =  'alpha.a'    '' '' 'ENDL0B'   'target'  -1.623900964E+00   1e1
    datum( 3) =  'beta.b'     '' '' 'ENDL0B'   'target'   4.416143920E+01   1e1
    datum( 4) =  'alpha.b'    '' '' 'ENDL0B'   'target'  -5.562722043E+00   1e1
    datum( 5) =  'eta.x'      '' '' 'ENDL0B'   'target'   0.000000000E+00   1e1
    datum( 6) =  'etap.x'     '' '' 'ENDL0B'   'target'   0.000000000E+00   1e1
/  


&tao_d2_data
        d2_data%name = 'HTR'
        universe = 1
        n_d1_data = 1
/
&tao_d1_data
        ix_d1_data = 1
        default_weight = 1
        d1_data%name = 'begtwiss'
        datum( 1) =  'beta.a'     '' '' 'HTRUNDB'   'target'  10  1e1
        datum( 2) =  'alpha.a'    '' '' 'HTRUNDB'   'target'   0  1e2
        datum( 3) =  'beta.b'     '' '' 'HTRUNDB'   'target'  10  1e1
        datum( 4) =  'alpha.b'    '' '' 'HTRUNDB'   'target'   0  1e2
        datum( 5) =  'eta.x'      '' '' 'HTRUNDB'   'target'   0  1e1
        datum( 6) =  'etap.x'     '' '' 'HTRUNDB'   'target'   0  1e2
/   





!-----------------------------------------
! BPM Orbit 

&tao_d2_data
    d2_data%name = 'orbit'
    universe = 1
    n_d1_data = 2
/    
    
&tao_d1_data
    ix_d1_data = 1
    default_weight = 1
    d1_data%name = 'x'
    default_data_type = 'bpm_orbit.x'
    default_data_source = 'lat'
    !search_for_lat_eles = "monitor::bpm*,monitor::rfb*" 
    datum(1:)%ele_name =  'BPM1B', 'BPM2B', 'BPM0H01', 'BPM0H04', 'BPM0H05', 'BPM0H08',
     'BPMH1', 'BPMH2', 'BPMHD01', 'BPMHD02', 'BPMHD03', 'BPMHD04',
     'BPMDG000', 'BPMDG001', 'BPMDG002', 'BPMDG003', 'BPMDG004', 'BPMDG005',
     'BPMDG0RF', 'BPMDG008', 'BPMDG009', 'BPMDG011', 'BPMDG012'
/

&tao_d1_data
    ix_d1_data = 2
    default_weight = 1
    d1_data%name = 'y'
    default_data_type = 'bpm_orbit.y'
    default_data_source = 'lat'
    !search_for_lat_eles = "monitor::bpm*,monitor::rfb*" 
    use_same_lat_eles_as = 'orbit.x'
/

!-----------------------------------------------------------------------------------------
!-----------------------------------------------------------------------------------------

&tao_var
	v1_var%name = 'begtwiss'
	default_step = 1e-4
	default_universe = '1'
	ix_min_var = 1
	ix_max_var = 6
	var(1:6)%ele_name  = 'beginning', 'beginning', 'beginning', 'beginning', 'beginning', 'beginning'
    var(1:6)%attribute = 'beta_a', 'alpha_a', 'beta_b', 'alpha_b', 'eta_x', 'etap_x'
    var(1)%low_lim = 0.01
    var(3)%low_lim = 0.01
/



!&tao_var
    v1_var%name = 'L0'
	default_step = 1e-4
	default_attribute = 'x'
	var(1:)%ele_name = 'O_L0'
/




