&tao_start
  n_universes = 1
  plot_file   ='$LCLS_LATTICE/bmad/tao/tao_plot.init '
  startup_file='$LCLS_LATTICE/bmad/tao/tao.startup'
/




!--------------------------------------------------------
&tao_design_lattice
  !unique_name_suffix="*::_##?"
  design_lattice(1)%file='sc_sxr.lat.bmad'
/

!------------------------------------------------------------------------
&tao_params
  !global%plot_on = T
  global%track_type = 'single'
  global%beam_timer_on = T
  global%random_engine = 'pseudo' ! or: 'quasi'
  global%de_lm_step_ratio = 1500
  global%optimizer = 'lmdif'
  global%n_opti_cycles = 100
  !---Bmad---
  bmad_com%radiation_damping_on = F
  bmad_com%radiation_fluctuations_on = T
/



&tao_beam_init
beam_init%random_engine = 'quasi'
ix_universe = 1
beam_saved_at =  "MARKER::*"
track_start = 'BEAM0'
!track_end = 'DBMARK82'
track_end = 'SXRSTART'
beam_init%position_file = '$LCLS_LATTICE/bmad/beams/FZ_100pC_10NOV17_scattered_5keV_resampled_100k.beam0'
!beam_init%position_file = 'beam_1.hdf5'
beam_init%center(1) = 0.0
beam_init%center(2) = 0.0
beam_init%center(3) = 0.0
beam_init%center(4) = 0.0
beam_init%center(5) = 0.0
beam_init%center(6) = 0.0

/


&tao_d2_data
        d2_data%name = 'L0'
        universe = 1
        n_d1_data = 2
/
&tao_d1_data
        ix_d1_data = 1
        default_weight = 1
        d1_data%name = 'energy'
        datum( 1) =  'orbit.e_tot'     '' '' 'ENDL0B'   'target'  100e6  1e1
/
&tao_d1_data
    ix_d1_data = 2
    d1_data%name = 'endtwiss'
    datum( 1) =  'beta.a'     '' '' 'ENDL0B'   'target'   2.124671319E+01   1e1
    datum( 2) =  'alpha.a'    '' '' 'ENDL0B'   'target'  -1.623900964E+00   1e1
    datum( 3) =  'beta.b'     '' '' 'ENDL0B'   'target'   4.416143920E+01   1e1
    datum( 4) =  'alpha.b'    '' '' 'ENDL0B'   'target'  -5.562722043E+00   1e1
    datum( 5) =  'eta.x'      '' '' 'ENDL0B'   'target'   0.000000000E+00   1e1
    datum( 6) =  'etap.x'     '' '' 'ENDL0B'   'target'   0.000000000E+00   1e1
/  


&tao_d2_data
        d2_data%name = 'HTR'
        universe = 1
        n_d1_data = 1
/
&tao_d1_data
        ix_d1_data = 1
        default_weight = 1
        d1_data%name = 'begtwiss'
        datum( 1) =  'beta.a'     '' '' 'HTRUNDB'   'target'  10   1e1
        datum( 2) =  'alpha.a'    '' '' 'HTRUNDB'   'target' 0  1e2
        datum( 3) =  'beta.b'     '' '' 'HTRUNDB'   'target'  10    1e1
        datum( 4) =  'alpha.b'    '' '' 'HTRUNDB'   'target'  0  1e2
        datum( 5) =  'eta.x'      '' '' 'HTRUNDB'   'target'   0  1e1
        datum( 6) =  'etap.x'     '' '' 'HTRUNDB'   'target'   0   1e2
/   


&tao_d2_data
        d2_data%name = 'BC1'
        universe = 1
        n_d1_data = 1
/
&tao_d1_data
        ix_d1_data = 1
        default_weight = 1
        d1_data%name = 'begtwiss'
        datum( 1) =  'beta.a'     '' '' 'BEGBC1B'   'target'  3.870395077E+01   1e1
        datum( 2) =  'alpha.a'    '' '' 'BEGBC1B'   'target'  4.476022866E-01  1e2
        datum( 3) =  'beta.b'     '' '' 'BEGBC1B'   'target'  3.109163641E+01     1e1
        datum( 4) =  'alpha.b'    '' '' 'BEGBC1B'   'target'  -7.975687433E-01  1e2
        datum( 5) =  'eta.x'      '' '' 'BEGBC1B'   'target'   0  1e1
        datum( 6) =  'etap.x'     '' '' 'BEGBC1B'   'target'   0   1e2
/   


&tao_d2_data
        d2_data%name = 'L1'
        universe = 1
        n_d1_data = 1
/
&tao_d1_data
    ix_d1_data = 1
    d1_data%name = 'endtwiss'
    datum( 1) =  'beta.a'     '' '' 'ENDL1B'   'target'   3.870395077E+01   1e1
    datum( 2) =  'alpha.a'    '' '' 'ENDL1B'   'target'   4.476022866E-01   1e1
    datum( 3) =  'beta.b'     '' '' 'ENDL1B'   'target'   3.109163641E+01   1e1
    datum( 4) =  'alpha.b'    '' '' 'ENDL1B'   'target'  -7.975687433E-01   1e1
    datum( 5) =  'eta.x'      '' '' 'ENDL1B'   'target'  -4.447171945E-18   1e1
    datum( 6) =  'etap.x'     '' '' 'ENDL1B'   'target'  -1.665944118E-18   1e1
/


&tao_d2_data
        d2_data%name = 'L2'
        universe = 1
        n_d1_data = 1
/
&tao_d1_data
    ix_d1_data = 1
    d1_data%name = 'endtwiss'
    datum( 1) =  'beta.a'     '' '' 'ENDL2B'   'target'   2.301739816E+02   1e1
    datum( 2) =  'alpha.a'    '' '' 'ENDL2B'   'target'  -3.315233808E+00   1e1
    datum( 3) =  'beta.b'     '' '' 'ENDL2B'   'target'   1.535195604E+01   1e1
    datum( 4) =  'alpha.b'    '' '' 'ENDL2B'   'target'  -2.950181911E-01   1e1
    datum( 5) =  'eta.x'      '' '' 'ENDL2B'   'target'  -1.435337641E-12   1e1
    datum( 6) =  'etap.x'     '' '' 'ENDL2B'   'target'   2.967880755E-14   1e1
/  


&tao_d2_data
        d2_data%name = 'L3'
        universe = 1
        n_d1_data = 1
/
&tao_d1_data
    ix_d1_data = 1
    d1_data%name = 'endtwiss'
    datum( 1) =  'beta.a'     '' '' 'ENDL3B'   'target'   4.500235329E+01   1e1
    datum( 2) =  'alpha.a'    '' '' 'ENDL3B'   'target'  -1.062939587E+00   1e1
    datum( 3) =  'beta.b'     '' '' 'ENDL3B'   'target'   1.749823135E+01   1e1
    datum( 4) =  'alpha.b'    '' '' 'ENDL3B'   'target'   5.236108174E-01   1e1
    datum( 5) =  'eta.x'      '' '' 'ENDL3B'   'target'  -2.998937169E-12   1e1
    datum( 6) =  'etap.x'     '' '' 'ENDL3B'   'target'  -1.001201770E-13   1e1
/




&tao_d2_data
        d2_data%name = 'r56'
        universe = 1
        n_d1_data = 1
/    
&tao_d1_data
        ix_d1_data = 1
        default_weight = 1
        d1_data%name = 'endtwiss'
        datum( 1) =  'r56_compaction'     'BEGHTR' '' 'ENDHTR' 
        datum( 2) =  'r56_compaction'     'BEGBC1B' '' 'ENDBC1B' 
        datum( 3) =  'r56_compaction'     'BEGBC2B' '' 'ENDBC2B'   
/



!-----------------------------------------
! BPM Orbit
! Auto-generated BPM datums using: $LCLS_LATTICE/bmad/conversion/tao/create_vars_and_datums.ipynb
        
&tao_d2_data
    d2_data%name = 'orbit'
    universe = 1
    n_d1_data = 3
/    
    
&tao_d1_data
    ix_d1_data = 1
    default_weight = 1
    d1_data%name = 'x'
    default_data_type = 'bpm_orbit.x'
    default_data_source = 'lat'
    !search_for_lat_eles = "monitor::bpm*,monitor::rfb*" 
    datum(1:)%ele_name =  'BPM1B', 'BPM2B', 'BPM0H01', 'BPM0H04', 'BPM0H05', 'BPM0H08',
     'BPMH1', 'BPMH2', 'BPMHD01', 'BPMHD02', 'BPMHD03', 'BPMHD04',
     'BPMDG000', 'BPMC001', 'BPMC002', 'BPMC003', 'BPMC004', 'BPMC005',
     'BPMC006', 'BPMC007', 'BPMC008', 'BPMC009', 'BPMC010', 'BPMC011',
     'BPMC012', 'BPM1C01', 'BPM11B', 'BPMC101', 'BPMC102', 'BPMC103',
     'BPMC104', 'BPMC105', 'BPMC106', 'BPMC107', 'BPMC108', 'BPMC109',
     'BPMC110', 'BPMC111', 'BPMC112', 'BPM2C01', 'BPM21B', 'BPME201',
     'BPME202', 'BPME203', 'BPME204', 'BPMX01', 'BPMX02', 'BPMDOG1', 'BPMDOG2',
     'BPMDOG3', 'BPMDOG4', 'BPMDOG5', 'BPMDOG6', 'BPMDOG7', 'BPMDOG8',
     'BPML1P', 'BPML2P', 'BPML3P', 'BPML4P', 'BPML5P', 'BPMBP10', 'BPMBP11',
     'BPMBP12', 'BPMBP13', 'BPMBP14', 'BPMBP15', 'BPMBP16', 'BPMBP17',
     'BPMBP18', 'BPMBP19', 'BPMBP20', 'BPMBP21', 'BPMBP22', 'BPMBP23',
     'BPMBP24', 'BPMBP25', 'BPMBP26', 'BPMBP27', 'BPMBP35', 'BPMBP28',
     'BPMSPH', 'BPMSP1', 'BPMSP2', 'BPMSPS', 'BPMSP1S', 'BPMSP2S', 'BPMSP3S',
     'BPMSP4S', 'BPMSP5S', 'BPMSP6S', 'BPMSP7S', 'BPMSP8S', 'BPMSP9S',
     'BPMBP36', 'BPMBP31', 'BPMBP32', 'BPMBP34', 'BPMDBL2', 'BPMDL11',
     'BPMDL12', 'BPMDL13', 'BPMDL15', 'BPMDL16', 'BPMDL17', 'BPMDL19',
     'BPMDL20', 'BPMDL21', 'BPMDL22', 'BPMVB1B', 'BPMVB3B', 'BPMVM3B',
     'BPMVM4B', 'BPMEM1B', 'BPMEM2B', 'BPMEM3B', 'BPMEM4B', 'BPME33B',
     'BPME34B', 'BPMUM1B', 'BPMUM2B', 'BPMUM3B', 'BPMUM4B', 'RFBSX16',
     'RFBSX19', 'RFBSX21', 'RFBSX24', 'RFBSX25', 'RFBSX26', 'RFBSX27',
     'RFBSX28', 'RFBSX29', 'RFBSX30', 'RFBSX31', 'RFBSX32', 'RFBSX33',
     'RFBSX34', 'RFBSX35', 'RFBSX36', 'RFBSX37', 'RFBSX38', 'RFBSX39',
     'RFBSX40', 'RFBSX41', 'RFBSX42', 'RFBSX43', 'RFBSX44', 'RFBSX45',
     'RFBSX46', 'RFBSX47', 'RFBSX51', 'BPMUE1B', 'BPMUE2B', 'BPMQDB', 'BPMDDB'
/

&tao_d1_data
    ix_d1_data = 2
    default_weight = 1
    d1_data%name = 'y'
    default_data_type = 'bpm_orbit.y'
    default_data_source = 'lat'
    !search_for_lat_eles = "monitor::bpm*,monitor::rfb*" 
    use_same_lat_eles_as = 'orbit.x'
/

&tao_d1_data
    ix_d1_data = 3
    default_weight = 1
    d1_data%name = 'charge'
    default_data_type = 'bunch_charge.live'
    default_data_source = 'beam'
    !search_for_lat_eles = "monitor::bpm*,monitor::rfb*" 
    use_same_lat_eles_as = 'orbit.x'
/





!-----------------------------------------
!-----------------------------------------------------------------------------------------

&tao_var
	v1_var%name = 'begtwiss'
	default_step = 1e-4
	default_universe = '1'
	ix_min_var = 1
	ix_max_var = 6
	var(1:6)%ele_name  = 'beginning', 'beginning', 'beginning', 'beginning', 'beginning', 'beginning'
    var(1:6)%attribute = 'beta_a', 'alpha_a', 'beta_b', 'alpha_b', 'eta_x', 'etap_x'
    var(1)%low_lim = 0.01
    var(3)%low_lim = 0.01
/



!&tao_var
    v1_var%name = 'L0'
	default_step = 1e-4
	default_attribute = 'x'
	var(1:)%ele_name = 'O_L0'
/

&tao_var
    v1_var%name = 'q.L1'
	default_step = 1e-4
	default_attribute = 'K1'
	var(1:)%ele_name = 'QC010', 'QC011','QC012', 'QCM02', 'QCM03'
/


&tao_var
    v1_var%name = 'q.L2'
	default_step = 1e-4
	default_attribute = 'K1'
	var(1:)%ele_name = 'QCM04', 'QCM08', 'QCM11', 'QCM15'
/

&tao_var
    v1_var%name = 'q.L3'
	default_step = 1e-4
	default_attribute = 'K1'
	var(1:)%ele_name = 'QCM16', 'QCM22', 'QCM29', 'QCM35'
/



!----------------------------------------
! Correctors
! Auto-generated corrector datums using: $LCLS_LATTICE/bmad/conversion/tao/create_vars_and_datums.ipynb
        
&tao_var
    v1_var%name = 'xcor'
    default_step = 1e-2
    default_attribute = 'bl_kick'
    var(1:)%ele_name =  'XC01B', 'XC02B', 'XC03B', 'XC04B', 'XC05B', 'XCM01', 'XC0H01',
     'XC0H03', 'XC0H05', 'XC0H07', 'XCHD01', 'XCHD03', 'XCC000', 'XCC004',
     'XCC006', 'XCC008', 'XCC010', 'XCC012', 'XCM02', 'XCM03', 'XC1C00', 'XCM12B',
     'XCC101', 'XCC104', 'XCC106', 'XCC108', 'XCC110', 'XCC112', 'XCM04', 'XCM05',
     'XCM06', 'XCM07', 'XCM08', 'XCM09', 'XCM10', 'XCM11', 'XCM12', 'XCM13', 'XCM14',
     'XCM15', 'XC2C00', 'XCE202', 'XCE204', 'XCM16', 'XCM17', 'XCM18', 'XCM19',
     'XCM20', 'XCM21', 'XCM22', 'XCM23', 'XCM24', 'XCM25', 'XCM26', 'XCM27', 'XCM28',
     'XCM29', 'XCM30', 'XCM31', 'XCM32', 'XCM33', 'XCM34', 'XCM35', 'XCX01',
     'XCDOG1', 'XCDOG3', 'XCDOG5', 'XCDOG7', 'XCL1P', 'XCL3P', 'XCL5P', 'XCBP11',
     'XCBP13', 'XCBP14', 'XCBP15', 'XCBP16', 'XCBP17', 'XCBP18', 'XCBP19',
     'XCBP20', 'XCBP21', 'XCBP22', 'XCBP23', 'XCBP24', 'XCBP25', 'XCBP26',
     'XCBP27', 'XCBP35', 'XCBP28', 'XCSP1', 'XCSP1S', 'XCSP3S', 'XCSP5S',
     'XCSP7S', 'XCSP9S', 'XCBP30', 'XCBP31', 'XCBP32', 'XCBP33', 'XCBP34',
     'XCDBL2', 'XCDL11', 'XCDL13', 'XCDL15', 'XCDL17', 'XCDL19', 'XCDL22',
     'XCVB2B', 'XCVM3B', 'XCEM1B', 'XCEM3B', 'XCE31B', 'XCXL1', 'XCE33B',
     'XCE35B', 'XCXL2', 'XCUM1B', 'XCUM3B', 'XCSX16', 'XCSX19', 'XCSX21',
     'XCSX24', 'XCSX26', 'XCSX27', 'XCSX28', 'XCSX29', 'XCSX30', 'XCSX31',
     'XCSX32', 'XCSX33', 'XCSX34', 'XCSX35', 'XCSX36', 'XCSX37', 'XCSX38',
     'XCSX39', 'XCSX40', 'XCSX41', 'XCSX42', 'XCSX43', 'XCSX44', 'XCSX45',
     'XCSX46', 'XCSX47', 'XCPEPX1', 'XCPEPX2', 'XCPEPX3', 'XCPEPX4', 'XCUE2B',
     'XCD3B', 'XCDDB'
/


&tao_var
    v1_var%name = 'ycor'
    default_step = 1e-2
    default_attribute = 'bl_kick'
    var(1:)%ele_name =  'YC01B', 'YC02B', 'YC03B', 'YC04B', 'YC05B', 'YCM01', 'YC0H01',
     'YC0H03', 'YC0H05', 'YC0H07', 'YCHD01', 'YCHD03', 'YCC000', 'YCC003',
     'YCC005', 'YCC007', 'YCC009', 'YCC011', 'YCM02', 'YCM03', 'YC1C00', 'YCM12B',
     'YCC101', 'YCC105', 'YCC107', 'YCC109', 'YCC111', 'YCM04', 'YCM05', 'YCM06',
     'YCM07', 'YCM08', 'YCM09', 'YCM10', 'YCM11', 'YCM12', 'YCM13', 'YCM14', 'YCM15',
     'YC2C00', 'YCE201', 'YCE203', 'YCM16', 'YCM17', 'YCM18', 'YCM19', 'YCM20',
     'YCM21', 'YCM22', 'YCM23', 'YCM24', 'YCM25', 'YCM26', 'YCM27', 'YCM28', 'YCM29',
     'YCM30', 'YCM31', 'YCM32', 'YCM33', 'YCM34', 'YCM35', 'YCX02', 'YCDOG0',
     'YCDOG2', 'YCDOG4', 'YCDOG6', 'YCDOG8', 'YCL2P', 'YCL4P', 'YCBP10', 'YCBP12',
     'YCBP13', 'YCBP14', 'YCBP15', 'YCBP16', 'YCBP17', 'YCBP18', 'YCBP19',
     'YCBP20', 'YCBP21', 'YCBP22', 'YCBP23', 'YCBP24', 'YCBP25', 'YCBP26',
     'YCBP27', 'YCBP35', 'YCBP28', 'YCSP2', 'YCSP2S', 'YCSP4S', 'YCSP6S',
     'YCSP8S', 'YCBP30', 'YCBP31', 'YCBP32', 'YCBP33', 'YCBP34', 'YCDBL1',
     'YCDL12', 'YCDL14', 'YCDL16', 'YCDL18', 'YCDL20', 'YCDL21', 'YCVB1B',
     'YCVB3B', 'YCVM4B', 'YCEM2B', 'YCEM4B', 'YCXL1', 'YCE32B', 'YCE34B', 'YCXL2',
     'YCE36B', 'YCUM2B', 'YCUM4B', 'YCSX16', 'YCSX19', 'YCSX21', 'YCSX24',
     'YCSX26', 'YCSX27', 'YCSX28', 'YCSX29', 'YCSX30', 'YCSX31', 'YCSX32',
     'YCSX33', 'YCSX34', 'YCSX35', 'YCSX36', 'YCSX37', 'YCSX38', 'YCSX39',
     'YCSX40', 'YCSX41', 'YCSX42', 'YCSX43', 'YCSX44', 'YCSX45', 'YCSX46',
     'YCSX47', 'YCUE1B', 'YCD3B', 'YCDDB'
/

!----------------------------------------

