&tao_start
  n_universes = 1
  plot_file   ='$LCLS_LATTICE/bmad/tao/tao_plot.init '
  startup_file='$LCLS_LATTICE/bmad/tao/tao.startup'
/




!--------------------------------------------------------
&tao_design_lattice
  !unique_name_suffix="*::_##?"
  design_lattice(1)%file='sc_bsyd.lat.bmad'
  !design_lattice(1)%slice_lattice = "BEAM0:HXRSTART"
/

!------------------------------------------------------------------------
&tao_params
  global%plot_on = T
  global%track_type = 'single'
  global%beam_timer_on = T
  global%random_engine = 'pseudo' ! or: 'quasi'
  global%de_lm_step_ratio = 1500
  global%optimizer = 'lmdif'
  global%n_opti_cycles = 100
  !---Bmad---
  bmad_com%radiation_damping_on = F
  bmad_com%radiation_fluctuations_on = T
/



!---------------------------------------------------------------------------------------
! Initial Beam

&tao_beam_init
ix_universe = 1
!saved_at =  "MARKER::*"
track_start = 'OTR0H04'
!track_end = ''
beam_init%n_particle = 1000
beam_init%random_engine = 'quasi' ! or 'pseudo'
beam_init%bunch_charge = 50.0e-12  
beam_init%a_norm_emit = 1.5e-6 
beam_init%b_norm_emit = 1.5e-6  
beam_init%n_bunch = 1     
beam_init%sig_pz = 1e-3
beam_init%sig_z = 0.8e-3
/





&tao_d2_data
        d2_data%name = 'L0B'
        universe = 1
        n_d1_data = 2
/
&tao_d1_data
        ix_d1_data = 1
        default_weight = 1
        d1_data%name = 'energy'
        datum( 1) =  'orbit.e_tot'     '' '' 'BEAM0'   'target'  100e6  1e1
/
&tao_d1_data
    ix_d1_data = 2
    d1_data%name = 'endtwiss'
    datum( 1) =  'beta.a'     '' '' 'BEAM0'   'target'   2.124671319E+01   1e1
    datum( 2) =  'alpha.a'    '' '' 'BEAM0'   'target'  -1.623900964E+00   1e1
    datum( 3) =  'beta.b'     '' '' 'BEAM0'   'target'   4.416143920E+01   1e1
    datum( 4) =  'alpha.b'    '' '' 'BEAM0'   'target'  -5.562722043E+00   1e1
    datum( 5) =  'eta.x'      '' '' 'BEAM0'   'target'   0.000000000E+00   1e1
    datum( 6) =  'etap.x'     '' '' 'BEAM0'   'target'   0.000000000E+00   1e1
/  

!---------------------------------------------------------------------------------------
! Q0H01

&tao_d2_data
        d2_data%name = 'Q0H01'
        universe = 1
        n_d1_data = 1
/
&tao_d1_data
        ix_d1_data = 1
        default_weight = 1
        d1_data%name = 'begtwiss'
        datum( 1) =  'beta.a'     '' '' 'D0H00B'   'target'  10  1e1
        datum( 2) =  'alpha.a'    '' '' 'D0H00B'   'target'   0  1e2
        datum( 3) =  'beta.b'     '' '' 'D0H00B'   'target'  10  1e1
        datum( 4) =  'alpha.b'    '' '' 'D0H00B'   'target'   0  1e2
        datum( 5) =  'eta.x'      '' '' 'D0H00B'   'target'   0  1e1
        datum( 6) =  'etap.x'     '' '' 'D0H00B'   'target'   0  1e2
/  



!---------------------------------------------------------------------------------------
! OTR0H04

&tao_d2_data
        d2_data%name = 'OTR0H04'
        universe = 1
        n_d1_data = 1
/
&tao_d1_data
        ix_d1_data = 1
        default_weight = 1
        d1_data%name = 'midtwiss'
        datum( 1) =  'beta.a'     '' '' 'OTR0H04'   'target'   5.01187794  1e1
        datum( 2) =  'alpha.a'    '' '' 'OTR0H04'   'target'   0.04874000  1e2
        datum( 3) =  'beta.b'     '' '' 'OTR0H04'   'target'   4.96994136  1e1
        datum( 4) =  'alpha.b'    '' '' 'OTR0H04'   'target'   0.00576731  1e2
        datum( 5) =  'eta.x'      '' '' 'OTR0H04'   'target'   0  1e1
        datum( 6) =  'etap.x'     '' '' 'OTR0H04'   'target'   0  1e2
/  

!---------------------------------------------------------------------------------------
! HTR

&tao_d2_data
        d2_data%name = 'HTR'
        universe = 1
        n_d1_data = 3
/


&tao_d1_data
        ix_d1_data = 1
        default_weight = 1
        d1_data%name = 'begtwiss'
        datum( 1) =  'beta.a'     '' '' 'BEGHTR'   'target' 20.61723837   1e1
        datum( 2) =  'alpha.a'    '' '' 'BEGHTR'   'target'  0.03679827   1e2
        datum( 3) =  'beta.b'     '' '' 'BEGHTR'   'target' 158.62864148    1e1
        datum( 4) =  'alpha.b'    '' '' 'BEGHTR'   'target'    -18.05565615  1e2
        datum( 5) =  'eta.x'      '' '' 'BEGHTR'   'target'   1e1
        datum( 6) =  'etap.x'     '' '' 'BEGHTR'   'target'    1e2
/   

&tao_d1_data
        ix_d1_data = 2
        default_weight = 1
        d1_data%name = 'midtwiss'
        datum( 1) =  'beta.a'     '' '' 'HTRUNDB'   'target'  10   1e1   ! Treaty point
        datum( 2) =  'alpha.a'    '' '' 'HTRUNDB'   'target' 0  1e2
        datum( 3) =  'beta.b'     '' '' 'HTRUNDB'   'target'  10    1e1
        datum( 4) =  'alpha.b'    '' '' 'HTRUNDB'   'target'  0  1e2
        datum( 5) =  'eta.x'      '' '' 'HTRUNDB'   'target'   0  1e1
        datum( 6) =  'etap.x'     '' '' 'HTRUNDB'   'target'   0   1e2
/   
&tao_d1_data
        ix_d1_data = 3
        default_weight = 1
        d1_data%name = 'endtwiss'
        datum( 1) =  'beta.a'     '' '' 'ENDHTR'   'target'      19.84202375   1e1
        datum( 2) =  'alpha.a'    '' '' 'ENDHTR'   'target'    6.98917068  1e2
        datum( 3) =  'beta.b'     '' '' 'ENDHTR'   'target'   18.92209774     1e1
        datum( 4) =  'alpha.b'    '' '' 'ENDHTR'   'target'      3.54847827  1e2
        datum( 5) =  'eta.x'      '' '' 'ENDHTR'   'target'    1e1
        datum( 6) =  'etap.x'     '' '' 'ENDHTR'   'target'     1e2
/   




!---------------------------------------------------------------------------------------
! BC1

&tao_d2_data
        d2_data%name = 'BC1'
        universe = 1
        n_d1_data = 2
/
&tao_d1_data
        ix_d1_data = 1
        default_weight = 1
        d1_data%name = 'begtwiss'
        datum( 1) =  'beta.a'     '' '' 'BEGBC1B'   'target'  3.870395077E+01   1e1
        datum( 2) =  'alpha.a'    '' '' 'BEGBC1B'   'target'  4.476022866E-01  1e2
        datum( 3) =  'beta.b'     '' '' 'BEGBC1B'   'target'  3.109163641E+01     1e1
        datum( 4) =  'alpha.b'    '' '' 'BEGBC1B'   'target'  -7.975687433E-01  1e2
        datum( 5) =  'eta.x'      '' '' 'BEGBC1B'   'target'   0  1e1
        datum( 6) =  'etap.x'     '' '' 'BEGBC1B'   'target'   0   1e2
/  

&tao_d1_data
        ix_d1_data = 2
        default_weight = 1
        d1_data%name = 'r56'
        datum( 1) =  'r56_compaction'     'BEGBC1B' '' 'ENDBC1B'  'target' 45e-3  1e1
/


!---------------------------------------------------------------------------------------
! COL1

&tao_d2_data
        d2_data%name = 'COL1'
        universe = 1
        n_d1_data = 1
/
&tao_d1_data
        ix_d1_data = 1
        default_weight = 1
        d1_data%name = 'endtwiss'
        datum( 1) =  'beta.a'     '' '' 'ENDCOL1'   'target'  25.77163820    1e1
        datum( 2) =  'alpha.a'    '' '' 'ENDCOL1'   'target' 0.86995449 1e2
        datum( 3) =  'beta.b'     '' '' 'ENDCOL1'   'target'   5.02337989     1e1
        datum( 4) =  'alpha.b'    '' '' 'ENDCOL1'   'target' -0.18284591  1e2
        datum( 5) =  'eta.x'      '' '' 'ENDCOL1'   'target'   0  1e1
        datum( 6) =  'etap.x'     '' '' 'ENDCOL1'   'target'   0   1e2
/  





!---------------------------------------------------------------------------------------
! BC2

&tao_d2_data
        d2_data%name = 'BC2'
        universe = 1
        n_d1_data = 2
/
&tao_d1_data
        ix_d1_data = 1
        default_weight = 1
        d1_data%name = 'begtwiss'
        datum( 1) =  'beta.a'     '' '' 'BEGBC2B'   'target'  3.870395077E+01   1e1
        datum( 2) =  'alpha.a'    '' '' 'BEGBC2B'   'target'  4.476022866E-01    1e2
        datum( 3) =  'beta.b'     '' '' 'BEGBC2B'   'target'  3.109163641E+01     1e1
        datum( 4) =  'alpha.b'    '' '' 'BEGBC2B'   'target'  -7.975687433E-01   1e2
        datum( 5) =  'eta.x'      '' '' 'BEGBC2B'   'target'   0  1e1
        datum( 6) =  'etap.x'     '' '' 'BEGBC2B'   'target'   0   1e2
/  

&tao_d1_data
        ix_d1_data = 2
        default_weight = 1
        d1_data%name = 'r56'
        datum( 1) =  'r56_compaction'     'BEGBC2B' '' 'ENDBC2B'  'target' 45e-3  1e1
/




!---------------------------------------------------------------------------------------
! EMIT2

&tao_d2_data
        d2_data%name = 'EMIT2'
        universe = 1
        n_d1_data = 1
/
&tao_d1_data
        ix_d1_data = 1
        default_weight = 1
        d1_data%name = 'endtwiss'
        datum( 1) =  'beta.a'     '' '' 'ENDEMIT2'   'target'  55.29630154    1e1
        datum( 2) =  'alpha.a'    '' '' 'ENDEMIT2'   'target'  1.50461172  1e2
        datum( 3) =  'beta.b'     '' '' 'ENDEMIT2'   'target'   7.84219456      1e1
        datum( 4) =  'alpha.b'    '' '' 'ENDEMIT2'   'target'  -0.39966385   1e2
        datum( 5) =  'eta.x'      '' '' 'ENDEMIT2'   'target'   0  1e1
        datum( 6) =  'etap.x'     '' '' 'ENDEMIT2'   'target'   0   1e2
/  





 

!---------------------------------------------------------------------------------------
! L1


&tao_d2_data
        d2_data%name = 'L1'
        universe = 1
        n_d1_data = 2
/

&tao_d1_data
        ix_d1_data = 1
        default_weight = 1
        d1_data%name = 'energy'
        datum( 1) =  'orbit.e_tot'     '' '' 'ENDL1B'   'target'  230e6  1e1
/

&tao_d1_data
    ix_d1_data = 2
    d1_data%name = 'endtwiss'
    datum( 1) =  'beta.a'     '' '' 'ENDL1B'   'target'   3.870395077E+01   1e1
    datum( 2) =  'alpha.a'    '' '' 'ENDL1B'   'target'   4.476022866E-01   1e1
    datum( 3) =  'beta.b'     '' '' 'ENDL1B'   'target'   3.109163641E+01   1e1
    datum( 4) =  'alpha.b'    '' '' 'ENDL1B'   'target'  -7.975687433E-01   1e1
    datum( 5) =  'eta.x'      '' '' 'ENDL1B'   'target'  -4.447171945E-18   1e1
    datum( 6) =  'etap.x'     '' '' 'ENDL1B'   'target'  -1.665944118E-18   1e1
/



!---------------------------------------------------------------------------------------
! L2

&tao_d2_data
        d2_data%name = 'L2'
        universe = 1
        n_d1_data = 2
/

&tao_d1_data
        ix_d1_data = 1
        default_weight = 1
        d1_data%name = 'energy'
        datum( 1) =  'orbit.e_tot'     '' '' 'ENDL2B'   'target'  1600e6  1e1
/

&tao_d1_data
    ix_d1_data = 2
    d1_data%name = 'endtwiss'
    datum( 1) =  'beta.a'     '' '' 'ENDL2B'   'target'   2.301739816E+02   1e1
    datum( 2) =  'alpha.a'    '' '' 'ENDL2B'   'target'  -3.315233808E+00   1e1
    datum( 3) =  'beta.b'     '' '' 'ENDL2B'   'target'   1.535195604E+01   1e1
    datum( 4) =  'alpha.b'    '' '' 'ENDL2B'   'target'  -2.950181911E-01   1e1
    datum( 5) =  'eta.x'      '' '' 'ENDL2B'   'target'  -1.435337641E-12   1e1
    datum( 6) =  'etap.x'     '' '' 'ENDL2B'   'target'   2.967880755E-14   1e1
/  


!---------------------------------------------------------------------------------------
! L3

&tao_d2_data
        d2_data%name = 'L3'
        universe = 1
        n_d1_data = 2
/


&tao_d1_data
        ix_d1_data = 1
        default_weight = 1
        d1_data%name = 'energy'
        datum( 1) =  'orbit.e_tot'     '' '' 'ENDL3B'   'target'  4000e6  1e1
/

&tao_d1_data
    ix_d1_data = 2
    d1_data%name = 'endtwiss'
    datum( 1) =  'beta.a'     '' '' 'ENDL3B'   'target'   4.500235329E+01   1e1
    datum( 2) =  'alpha.a'    '' '' 'ENDL3B'   'target'  -1.062939587E+00   1e1
    datum( 3) =  'beta.b'     '' '' 'ENDL3B'   'target'   1.749823135E+01   1e1
    datum( 4) =  'alpha.b'    '' '' 'ENDL3B'   'target'   5.236108174E-01   1e1
    datum( 5) =  'eta.x'      '' '' 'ENDL3B'   'target'  -2.998937169E-12   1e1
    datum( 6) =  'etap.x'     '' '' 'ENDL3B'   'target'  -1.001201770E-13   1e1
/




&tao_d2_data
        d2_data%name = 'r56'
        universe = 1
        n_d1_data = 1
/    
&tao_d1_data
        ix_d1_data = 1
        default_weight = 1
        d1_data%name = 'endtwiss'
        datum( 1) =  'r56_compaction'     'BEGHTR' '' 'ENDHTR' 
        datum( 2) =  'r56_compaction'     'BEGBC1B' '' 'ENDBC1B' 
        datum( 3) =  'r56_compaction'     'BEGBC2B' '' 'ENDBC2B'   
/



!-----------------------------------------
! BPM Orbit
! Auto-generated BPM datums using: $LCLS_LATTICE/bmad/conversion/tao/create_vars_and_datums.ipynb
        
&tao_d2_data
    d2_data%name = 'orbit'
    universe = 1
    n_d1_data = 3
/    
    
&tao_d1_data
    ix_d1_data = 1
    default_weight = 1
    d1_data%name = 'x'
    default_data_type = 'bpm_orbit.x'
    default_data_source = 'lat'
    !search_for_lat_eles = "monitor::bpm*,monitor::rfb*,monitor::cmb*" 
    datum(1:)%ele_name =  'BPM1B', 'BPM2B', 'CMB01', 'BPM0H01', 'BPM0H04', 'BPM0H05',
     'BPM0H08', 'BPMH1', 'BPMH2', 'BPMHD01', 'BPMHD02', 'BPMHD03', 'BPMHD04',
     'BPMDG000', 'BPMC001', 'BPMC002', 'BPMC003', 'BPMC004', 'BPMC005',
     'BPMC006', 'BPMC007', 'BPMC008', 'BPMC009', 'BPMC010', 'BPMC011',
     'BPMC012', 'CMB02', 'CMB03', 'CMBH1', 'CMBH2', 'BPM1C01', 'BPM11B', 'BPMC101',
     'BPMC102', 'BPMC103', 'BPMC104', 'BPMC105', 'BPMC106', 'BPMC107',
     'BPMC108', 'BPMC109', 'BPMC110', 'BPMC111', 'BPMC112', 'CMB04', 'CMB05',
     'CMB06', 'CMB07', 'CMB08', 'CMB09', 'CMB10', 'CMB11', 'CMB12', 'CMB13', 'CMB14',
     'CMB15', 'BPM2C01', 'BPM21B', 'BPME201', 'BPME202', 'BPME203',
     'BPME204', 'CMB16', 'CMB17', 'CMB18', 'CMB19', 'CMB20', 'CMB21', 'CMB22', 'CMB23',
     'CMB24', 'CMB25', 'CMB26', 'CMB27', 'CMB28', 'CMB29', 'CMB30', 'CMB31', 'CMB32',
     'CMB33', 'CMB34', 'CMB35', 'BPMX01', 'BPMX02', 'BPMDOG1', 'BPMDOG2',
     'BPMDOG3', 'BPMDOG4', 'BPMDOG5', 'BPMDOG6', 'BPMDOG7', 'BPMDOG8',
     'BPML1P', 'BPML2P', 'BPML3P', 'BPML4P', 'BPML5P', 'BPMBP10', 'BPMBP11',
     'BPMBP12', 'BPMBP13', 'BPMBP14', 'BPMBP15', 'BPMBP16', 'BPMBP17',
     'BPMBP18', 'BPMBP19', 'BPMBP20', 'BPMBP21', 'BPMBP22', 'BPMBP23',
     'BPMBP24', 'BPMBP25', 'BPMBP26', 'BPMBP27', 'BPMBP35', 'BPMBP28',
     'BPMSPH', 'BPMSP1', 'BPMSP2', 'BPMSPS', 'BPMSP1D', 'BPMDAS', 'BPMSP2D',
     'BPMSP3D', 'BPMSP4D', 'BPMSP5D'
    datum(1:)%meas = 0
/

&tao_d1_data
    ix_d1_data = 2
    default_weight = 1
    d1_data%name = 'y'
    default_data_type = 'bpm_orbit.y'
    default_data_source = 'lat'
    !search_for_lat_eles = "monitor::bpm*,monitor::rfb*,monitor::cmb*" 
    use_same_lat_eles_as = 'orbit.x'
    datum(1:)%meas = 0
/

&tao_d1_data
    ix_d1_data = 3
    default_weight = 1
    d1_data%name = 'charge'
    default_data_type = 'bunch_charge.live'
    default_data_source = 'beam'
    !search_for_lat_eles = "monitor::bpm*,monitor::rfb*,monitor::cmb*" 
    use_same_lat_eles_as = 'orbit.x'
/





!-----------------------------------------
!-----------------------------------------------------------------------------------------

&tao_var
	v1_var%name = 'begtwiss'
	default_step = 1e-4
	default_universe = '1'
	ix_min_var = 1
	ix_max_var = 6
	var(1:6)%ele_name  = 'beginning', 'beginning', 'beginning', 'beginning', 'beginning', 'beginning'
    var(1:6)%attribute = 'beta_a', 'alpha_a', 'beta_b', 'alpha_b', 'eta_x', 'etap_x'
    var(1)%low_lim = 0.01
    var(3)%low_lim = 0.01
/



&tao_var
    v1_var%name = 'gradient_L0'
	default_step = 1e-4
	default_attribute = 'gradient'
	search_for_lat_eles = 'lcavity::cavl01*'
	!var(1:)%ele_name = 'O_L0'
/
&tao_var
    v1_var%name = 'phi0_L0'
	default_step = 1e-4
	default_attribute = 'phi0'
	search_for_lat_eles = 'lcavity::cavl01*'
	!var(1:)%ele_name = 'O_L0'
/

&tao_var
    v1_var%name = 'q_HTR'
	default_step = 1e-4
	default_attribute = 'K1'
	search_for_lat_eles = 'quad::Q0H*'
/

&tao_var
    v1_var%name = 'q_L1'
	default_step = 1e-4
	default_attribute = 'K1'
	var(1:)%ele_name = 'QC010', 'QC011','QC012', 'QCM02', 'QCM03'
/


&tao_var
    v1_var%name = 'q_L2'
	default_step = 1e-4
	default_attribute = 'K1'
	var(1:)%ele_name = 'QCM04', 'QCM08', 'QCM11', 'QCM15'
/

&tao_var
    v1_var%name = 'q_L3'
	default_step = 1e-4
	default_attribute = 'K1'
	var(1:)%ele_name = 'QCM17', 'QCM22', 'QCM29', 'QCM35'
/



&tao_var
    v1_var%name = 'linac_phase'
	default_step = 0.1
	default_attribute = 'phase_deg'
	var(1:)%ele_name = 'SC_L1', 'SC_L1H', 'SC_L2', 'SC_L3'
/

&tao_var
    v1_var%name = 'q_COL1'
	default_step = 1e-4
	default_attribute = 'K1'
	var(1:)%ele_name = 'QC101', 'QC102', 'QC103', 'QC104'
/

&tao_var
    v1_var%name = 'q_EMIT2'
	default_step = 1e-4
	default_attribute = 'K1'
	var(1:)%ele_name = 'QE201', 'QE202', 'QE203', 'QE204'
/


&tao_var
    v1_var%name = 'bc1'
    default_step = 0.01
    default_attribute = 'angle_deg'
    var(1:)%low_lim = -8.35
    var(1:)%high_lim = 0
    var(1:)%ele_name = 'SC_BC1'
/

&tao_var
    v1_var%name = 'bc2'
    default_step = 0.01
    default_attribute = 'angle_deg'
    var(1:)%low_lim =  0 
    var(1:)%high_lim =  9.1
    var(1:)%ele_name = 'SC_BC2'
/


!----------------------------------------
! Correctors
! Auto-generated corrector datums using: $LCLS_LATTICE/bmad/conversion/tao/create_vars_and_datums.ipynb
        
&tao_var
    v1_var%name = 'xcor'
    default_step = 1e-2
    default_attribute = 'bl_kick'
    var(1:)%ele_name =  'XC01B', 'XC02B', 'XC03B', 'XC04B', 'XC05B', 'XCM01', 'XC0H01',
     'XC0H03', 'XC0H05', 'XC0H07', 'XCHD01', 'XCHD03', 'XCC000', 'XCC004',
     'XCC006', 'XCC008', 'XCC010', 'XCC012', 'XCM02', 'XCM03', 'XC1C00', 'XCM12B',
     'XCC101', 'XCC104', 'XCC106', 'XCC108', 'XCC110', 'XCC112', 'XCM04', 'XCM05',
     'XCM06', 'XCM07', 'XCM08', 'XCM09', 'XCM10', 'XCM11', 'XCM12', 'XCM13', 'XCM14',
     'XCM15', 'XC2C00', 'XCE202', 'XCE204', 'XCM16', 'XCM17', 'XCM18', 'XCM19',
     'XCM20', 'XCM21', 'XCM22', 'XCM23', 'XCM24', 'XCM25', 'XCM26', 'XCM27', 'XCM28',
     'XCM29', 'XCM30', 'XCM31', 'XCM32', 'XCM33', 'XCM34', 'XCM35', 'XCX01',
     'XCDOG1', 'XCDOG3', 'XCDOG5', 'XCDOG7', 'XCL1P', 'XCL3P', 'XCL5P', 'XCBP11',
     'XCBP13', 'XCBP14', 'XCBP15', 'XCBP16', 'XCBP17', 'XCBP18', 'XCBP19',
     'XCBP20', 'XCBP21', 'XCBP22', 'XCBP23', 'XCBP24', 'XCBP25', 'XCBP26',
     'XCBP27', 'XCBP35', 'XCBP28', 'XCSP1', 'XCSP1D', 'XCSP3D', 'BKXRASD'
/


&tao_var
    v1_var%name = 'ycor'
    default_step = 1e-2
    default_attribute = 'bl_kick'
    var(1:)%ele_name =  'YC01B', 'YC02B', 'YC03B', 'YC04B', 'YC05B', 'YCM01', 'YC0H01',
     'YC0H03', 'YC0H05', 'YC0H07', 'YCHD01', 'YCHD03', 'YCC000', 'YCC003',
     'YCC005', 'YCC007', 'YCC009', 'YCC011', 'YCM02', 'YCM03', 'YC1C00', 'YCM12B',
     'YCC101', 'YCC105', 'YCC107', 'YCC109', 'YCC111', 'YCM04', 'YCM05', 'YCM06',
     'YCM07', 'YCM08', 'YCM09', 'YCM10', 'YCM11', 'YCM12', 'YCM13', 'YCM14', 'YCM15',
     'YC2C00', 'YCE201', 'YCE203', 'YCM16', 'YCM17', 'YCM18', 'YCM19', 'YCM20',
     'YCM21', 'YCM22', 'YCM23', 'YCM24', 'YCM25', 'YCM26', 'YCM27', 'YCM28', 'YCM29',
     'YCM30', 'YCM31', 'YCM32', 'YCM33', 'YCM34', 'YCM35', 'YCX02', 'YCDOG0',
     'YCDOG2', 'YCDOG4', 'YCDOG6', 'YCDOG8', 'YCL2P', 'YCL4P', 'YCBP10', 'YCBP12',
     'YCBP13', 'YCBP14', 'YCBP15', 'YCBP16', 'YCBP17', 'YCBP18', 'YCBP19',
     'YCBP20', 'YCBP21', 'YCBP22', 'YCBP23', 'YCBP24', 'YCBP25', 'YCBP26',
     'YCBP27', 'YCBP35', 'YCBP28', 'YCSP2', 'YCSP2D', 'YCSP4D', 'BKYRASD'
/

!----------------------------------------



