name: TestsDev

on:
  push:

jobs:
  build:
    runs-on: "ubuntu-latest"
    steps:
      - uses: actions/checkout@v2
      - uses: conda-incubator/setup-miniconda@v2
        with:
          python-version: 3.9
          miniforge-variant: Mambaforge 
          channels: conda-forge
          channel-priority: true
          
      - name: Install dependencies
        run: |
          mamba install pytest pytao bmad

      - name: Fetch executables for testing
        uses: slaclab/accel-test-exec-fetcher@v1.0

      # This step can be removed, just ensuring it is working properly
      - name: Check mad8s version
        run: mad8s --version
        shell: bash
          
      - name: Run tests
        shell: bash -l {0}
        run: |
          conda activate base
          export LCLS_LATTICE=$GITHUB_WORKSPACE
          #pytest python/tests/ -v    
          echo $LCLS_LATTICE
          cd mad
          echo "running mad8s"
          mad8s < CI-Testing.mad8
          echo $?
          echo "testing .twiss"
          test -f SC_BSYD_GUN_CI.twiss 
          echo $?
        
