name: Publish Documentation
on:
  push:
  pull_request:
    branches:
      - '**'
jobs:
  deploy:
    if: ${{ github.repository == 'slaclab/lcls-lattice' }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        python-version: [3.9]
    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5  #v4
        with:
          fetch-depth: 0
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@e9aba2c848f5ebd159c070c61ea2c4e2b122355e #v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          sudo apt install python3-testresources
          pip install -U setuptools wheel
          pip install -U -r docs-requirements.txt
          pip install -U -r requirements.txt
      - name: Build Docs
        run: |
          mkdocs build
      - name: Deploy to gh-pages
        uses: peaceiris/actions-gh-pages@4a2e02b36f31d8974a0d09d3bb9f3172aa2d0d0d #v3
        if: github.ref == 'refs/heads/master' || startsWith(github.ref, 'refs/tags')
        with:
          deploy_key: ${{ secrets.SELF_SSH_DEPLOY_KEY }}
          publish_dir: ./site/
