name: Make Artifacts

on:
  pull_request:
  push:
  release:
    types:
      - published

jobs:
  build:
    runs-on: ubuntu-22.04
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.12"]

    name: Make Artifacts

    env:
      LCLS_LATTICE: ${{ github.workspace }}

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
        with:
          ssh-key ${{secrets.SELF_SSH_DEPLOY_KEY}}
      - uses: ./.github/actions/conda-setup
        with:
          python-version: ${{ matrix.python-version }}
          extras: "dev"
      - name: Test environment conda package list
        shell: bash -l {0}
        run: |
          conda list

      - name: Run plot generation script
        shell: bash -l {0}
        run: |
          echo -e '## Plotting results\n\n```' >> "$GITHUB_STEP_SUMMARY"
          python/scripts/make_plots.py 2>&1 | tee -a "$GITHUB_STEP_SUMMARY"
          echo '```' >> "$GITHUB_STEP_SUMMARY"

      - name: Add plots and commit to branch
        run: |
          mv beta_*.png docs/plots
          git config --global user.name 'Github Action'
          git config --global user.email 'mpe@slac.stanford.edu'
          git add docs/plots/beta_*.png
          git commit -m "Adding Twiss plots for each lattice"
          git push
