name: Make Optics Plots

on:
  workflow_dispatch:
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-22.04
    strategy:
      fail-fast: false

    name: Make Artifacts

    env:
      LCLS_LATTICE: ${{ github.workspace }}

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ssh-key: ${{secrets.SELF_SSH_DEPLOY_KEY}}

      - uses: ./.github/actions/conda-setup
        with:
          python-version: "3.12"

      - name: Test environment conda package list
        shell: bash -l {0}
        run: |
          conda list

      - name: Run Bmad (pytao) plot generation script
        shell: bash -l {0}
        run: |
          python/scripts/make_bmad_plots.py
          mv beta_*.png docs/plots

      - name: Fetch special SLAC executables
        uses: slaclab/accel_unit_test_execs@v1.2

      - name: Check mad8s version
        shell: bash -l {0}
        run: |
          set -o pipefail
          cd mad
          ../mad8s <<< "STOP" | grep -qvz Error
          cd ..
          python/scripts/make_mad_plots.py
          mv beta_*.png docs/plots
      
      - name: Make residual plots
        shell: bash -l {0}
        run: |
          python/scripts/residuals.py
          mv residual_*.png docs/plots

      - name: Add plots and commit to branch
        run: |
          git config --global user.name 'Github Action'
          git config --global user.email '\<\>'
          git add docs/plots/*.png
          ( git commit -m "Adding Twiss plots for each lattice [skip ci]" && git push || true )

