name: Make Artifacts

on:
  pull_request:
  push:
  release:
    types:
      - published

jobs:
  build:
    runs-on: ubuntu-22.04
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.12"]

    name: Make Artifacts

    env:
      LCLS_LATTICE: ${{ github.workspace }}

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: ./.github/actions/conda-setup
        with:
          python-version: ${{ matrix.python-version }}
          extras: "dev"
      - name: Test environment conda package list
        shell: bash -l {0}
        run: |
          conda list

      - name: Fetch special SLAC executables
        uses: slaclab/accel_unit_test_execs@v1.2

      - name: Check mad8s version
        shell: bash -l {0}
        run: |
          echo -e '# testing if mad8s is functional' >> "$GITHUB_STEP_SUMMARY"
          set -o pipefail
          cd mad
          ../mad8s <<< "STOP" | grep -qvz Error

      - name: Run plot generation script
        shell: bash -l {0}
        run: |
          echo -e '## Plotting results\n\n```' >> "$GITHUB_STEP_SUMMARY"
          python/scripts/make_plots.py 2>&1 | tee -a "$GITHUB_STEP_SUMMARY"
          echo '```' >> "$GITHUB_STEP_SUMMARY"
