name: publish-data

on:
  push:
    branches:
      - master

jobs:
  build:
    if: ${{ github.repository == 'slaclab/lcls-lattice' }}
    runs-on: ubuntu-latest
    name: Publish lattice to lcls-lattice-data
    steps:
      - uses: actions/checkout@v3
        with:
          ref: master
      - uses: conda-incubator/setup-miniconda@v2
        with:
          auto-activate-base: true
          python-version: 3.9
          channels: conda-forge,anaconda
          channel-priority: flexible
      - name: Run lattice export
        shell: bash -l {0}
        run: |
          conda config --set always_yes yes --set changeps1 no
          conda install -c conda-forge pytao bmad
          mkdir ${{ github.workspace }}/lattice-data
          export LCLS_LATTICE=$(pwd)
          python python/scripts/export/export_lattice.py --source $(pwd) --dest ${{ github.workspace }}/lattice-data
          echo "lattice_data_dir=${{ github.workspace }}/lattice-data" >> $GITHUB_ENV
      - name: Copy tests and CI workflow
        shell: bash -l {0}
        run: |
          cp -r tests/ ${{ github.workspace }}/lattice-data/tests
          mkdir -p ${{ github.workspace }}/lattice-data/.github/worklflows
          cp .github/worklflows/ci.yml ${{ github.workspace }}/lattice-data/.github/worklflows/ci.yml

      - name: Push directory to lcls-lattice-data
        uses: cpina/github-action-push-to-another-repository@v1.4.1
        env:
          API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
        with:
          source-directory: lattice-data
          destination-github-username: slaclab
          destination-repository-name: lcls-lattice-data
          user-email: ${{ secrets.LCLS_LATTICE_DATA_USER_EMAIL }}
          target-branch: main
          commit-message: ${{ github.event.head_commit.message }}

