name: tag-lcls-lattice-data

on:
  push:
    tags:
      - '*'

jobs:
  build:
    if: ${{ github.repository == 'slaclab/lcls-lattice' }}
    runs-on: ubuntu-latest
    name: Sync tag to lcls-lattice data
    steps:
      - name: Create lcls-lattice-data tag
        run: |
          git config --global user.email ${{ secrets.LCLS_LATTICE_DATA_USER_EMAIL }}
          git config --global user.name slaclab
          git clone --single-branch --branch main "https://slaclab:${{ secrets.API_TOKEN_GITHUB }}@github.com/slaclab/lcls-lattice-data.git" 
          cd lcls-lattice-data 
          git tag  -a ${{ github.ref_name }} -m "Syncing with lcls-lattice tag ${{ github.ref_name }}"
          git push origin ${{ github.ref_name }}
