name: Run prod tests

on:
  pull_request:
  push:
  release:
    types:
      - published

jobs:
  build:
    runs-on: ubuntu-22.04
    strategy:
      fail-fast: false

    name: Test Suite

    env:
      LCLS_LATTICE: ${{ github.workspace }}

    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5  #v4
        with:
          fetch-depth: 0
      - uses: ./.github/actions/conda-setup
        with:
          filename: "environment-prod.yml"
          env_name: "lcls-lattice-prod"
          extras: ""
      - name: Test environment conda package list
        shell: bash -l {0}
        run: |
          conda list

      - name: Fetch special SLAC executables
        uses: slaclab/accel_unit_test_execs@7992e10995d62bf02cc32c4d9b130789defd6dae #v1.2

      - name: Check mad8s version
        shell: bash -l {0}
        run: |
          echo -e '# testing if mad8s is functional' >> "$GITHUB_STEP_SUMMARY"
          set -o pipefail
          cd mad
          ../mad8s <<< "STOP" | grep -qvz Error

      - name: Run unit tests
        shell: bash -l {0}
        run: |
          echo -e '## Test results\n\n```' >> "$GITHUB_STEP_SUMMARY"
          pytest -v 2>&1 | tee -a "$GITHUB_STEP_SUMMARY"
          echo '```' >> "$GITHUB_STEP_SUMMARY"
